### ISSUE TITLE
Preenchimento do Formulário - Expandir Tudo

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#10]
Ao clicar em "expandir tudo" no cadastro de uma iniciativa em uma coleção, ao preencher um dos ítens o sistema fecha todos novamente. 
Para ilustrar, eu fiz o cadastro aqui: http://medialab.ufg.br/democraciadigital/iniciativas/#
Testei com categoria e com texto, só com categoria que da problema. 
O problema ocorre quando tem categoria atrelada tb.

**Comment by juliannyasilva** [comment]
Verificado, e este site não esta mais disponível, assumindo consequentemente que foi corrigido.
