### ISSUE TITLE
[IBRAM]  - Visualização de Descarte(Baixa)

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#100]
Cenário: https://docs.google.com/document/d/1zfV1HbVlnpxLcmqsS-NhzOKUWki3Q_jCRnrgpsgMKAY/edit#heading=h.8ga297mlc0u1

Caso 1: Lixeira de descarte diferente do padrão das outras, além de não dar opções de restauração e exclusão permanente, a paginação dos registros não esta correta, as colunas diferentes do esperado (Número, modo, data, n° processo).

Caso 2: Sistema não trabalha validação de mascaras de datas, permitindo adição de itens com datas erradas.

Caso 3: Colunas da tabela de descarte errada, uma delas ate sem nomenclatura, sendo o espero as seguintes colunas: Número, modo, data, n° processo;

Caso 4: As ações do item erradas sendo que não possui opção de alterar um item.

Caso 5: As buscas em descarte não esta trazendo os resultados corretamente, não trazendo um resultado se informando parte de seu nome.

**Comment by juliannyasilva** [comment]
Caso 1: Na lixeira esta errada a sequencia das colunas e faltando a coluna "numero", sendo a sequencia correta: Numero, modo, data e  n° do processo. Neste caso não existe a coluna "ações".

Caso 2: corrigido.

Caso 3: A tabela descarte esta com a sequencia das colunas erradas e faltando a coluna "numero".

Caso 4: Não permite a opções alterar item.

Caso 5: pesquisa simples é feita em quais campos?

Caso 6: Um membro consegue cancelar um item criado por um administrador. (é ou não pra permitir?).

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.

**Comment by juliannyasilva** [comment]
Retorno: renomear o campo 'Cancelamento' na visualização de um descarte cancelado (na lixeira) para 'Motivo do Cancelamento'.

**Comment by eduardohumberto** [comment]
O metadado cancelamento é um composto que possui o metadado motivo como filho,  há uma série de implicações no plugin respeitando essa estrutura de composição, talvez por não estar aparecendo o valor do motivo ( mesmo do caso #104 ) gerou essa confusão.

**Comment by juliannyasilva** [comment]
Resolvido, mantendo a mesma hierarquia por fins de implicações complicadas no plugin.
