### ISSUE TITLE
[IBRAM]  - Adição de Coleções

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#101]
Caso 1: De acordo com os requisitos de desenvolvimento não era pra existir os campos "miniatura" e "anexos" na adição de um conjunto.

Caso 2: De acordo com os requisitos o campo 'bens' campo era para disponibilizar opções de adição de novos bens bem como sua remoção, e o sistema não disponibiliza tais opções.

Caso 3: de acordo com os requisitos o campo 'conjuntos de bens' era para disponibilizar opções de adição de novos conjuntos de bens bem como sua remoção, e o sistema não disponibiliza tais opções.

Caso 4: campos 'bens' e 'conjuntos de bens' não atende a regra 106 e 107 respectivamente.

**Comment by juliannyasilva** [comment]
Caso 1: ainda não configurado.

Caso 4: os filtros não atende a regra 106. 

![image](https://user-images.githubusercontent.com/11639242/28730728-a2642e44-73a7-11e7-9c05-2918a0fcf6ed.png)

Caso 5: permite adicionar uma coleção com mesmo nome de uma coleção excluída. No qual restaurando a coleção excluída causa uma duplicação.

**Comment by eduardohumberto** [comment]
Caso 1: Basta entrar em layout, na última aba Estilo da submissão do item e desmarcar 'Habilitar visualização de imagem e anexo'

**Comment by leogermani** [comment]
VOltando pra validação depois do comentário do @eduardohumberto

**Comment by juliannyasilva** [comment]
Retornando para pronto pra começar, pois o caso 4 ainda não foi resolvido.

**Comment by eduardohumberto** [comment]
Caso 4 segue o exemplo do comentário feito no caso #95

**Comment by juliannyasilva** [comment]
Configurando layout retirando miniatura e anexos da interface.

**Comment by juliannyasilva** [comment]
Caso 4: Não persiste os metadados de busca da categoria "situação-bem".

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
