### ISSUE TITLE
[IBRAM] - Alteração de Assunto

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#103]
Caso 1: Na alteração de um assunto, ao informar no campo "assunto" uma informação já cadastrada, o sistema verifica que já existe e apaga o conteúdo do campo, mas se informar a mesma informações novamente, duplicando, e mandar salvar o sistema persiste.

Correção: De acordo com as orientações de desenvolvimento não permitir alterar um assunto com informação já castrada.

**Comment by walisonjose** [comment]
O sistema notificou que o assunto inserido era inválido, não salvou a alteração mas seguiu o fluxo de execução como se tivesse salvo a alteração retornando também um feedback positivo.

**Comment by juliannyasilva** [comment]
Não verificou inconsistências.
