### ISSUE TITLE
[IBRAM]  - Visualização de Desaparecimento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#104]
Caso 1: Lixeira de desaparecimento esta diferente do padrão das outras, além de não dar opções de restauração e exclusão permanente, a paginação dos registros não esta correta, as colunas diferentes do esperado (Número, tipo , data do desaparecimento, n° processo).

Caso 2: Sistema não trabalha validação de mascaras de datas, permitindo adição de itens com datas erradas.

Caso 3: Colunas da tabela de desaparecimento errada, uma delas esta sem nomenclatura, sendo o espero as seguintes colunas: Número, tipo , data do desaparecimento, n° processo;

Caso 4: As ações do item erradas sendo que não possui opção de alterar um item.

Caso 5: As buscas em desaparecimento não esta trazendo os resultados corretamente, e não trazendo um resultado se informando parte de seu nome.

**Comment by juliannyas** [comment]
Configurado o layout retirando os campos imagem e anexos.

**Comment by juliannyasilva** [comment]
Caso 1: Na lixeira esta errada a sequencia das colunas e faltando a coluna "numero", sendo a sequencia correta: Numero, tipo, data de desaparecimento e n° do processo. Neste caso não existe a coluna "ações".

Caso 3: A tabela desaparecimento esta com a sequencia das colunas erradas e faltando a coluna "numero". 

Caso 6: Um membro consegue cancelar um item criado por um administrador ? (é pra permitir?).

**Comment by r-guimaraes** [comment]
Caso 1 e 3: Configurações de Layout

**Comment by r-guimaraes** [comment]
Caso 6 Arrumado

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.

**Comment by juliannyasilva** [comment]
Retorno:
- [ ] Não esta trazendo o valor do motivo do cancelamento na visualização de um desaparecimento cancelado (na lixeira) no metadado "Cancelamento".
- [ ] Renomear o campo 'Cancelamento' na visualização de um desaparecimento cancelado (na lixeira) para 'Motivo do Cancelamento'.

**Comment by eduardohumberto** [comment]
"Não esta trazendo o valor do motivo do cancelamento na visualização de um desaparecimento cancelado (na lixeira) no metadado "Cancelamento".'

**Erro a ser corrigido**

Renomear o campo 'Cancelamento' na visualização de um desaparecimento cancelado (na lixeira) para 'Motivo do Cancelamento'.

**Olhar comentário do caso #100**

**Comment by juliannyasilva** [comment]
Retornos: 
- Tela inicial da coleção
Para todos os tipos de máscara de data aproximada a informação esta sendo exibida incorreta
na coluna: Data do desaparecimento.
- Tela inicial da lixeira
Para todos os tipos de máscara de data aproximada a informação esta sendo exibida incorreta
na coluna: Data do desaparecimento.

**Comment by eduardohumberto** [comment]
verificar se a instalação ibram esta atualizado!

**Comment by juliannyasilva** [comment]
Resolvido.
