### ISSUE TITLE
[IBRAM]  - Cancelamento de Desaparecimento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#105]
Caso 1: O sistema não recupera o desaparecimento de bens com suas informações bloqueadas para edição.

Caso 2: O sistema permite cancelar um desaparecimento de bens informando um espaço em branco no campo "motivo".

**Comment by juliannyasilva** [comment]
Não verificado inconsistências.

**Comment by juliannyasilva** [comment]
![image](https://user-images.githubusercontent.com/11639242/28795439-3864d53c-7610-11e7-9abf-96183b15f075.png)

De acordo com a regra 116, ao cancelar um desaparecimento o sistema não esta retornando os "bens envolvidos" aos seus estados anteriores. Ou seja, não retornando os campos "situação" e e "tipo de situação" aos valores no ato do cadastro do bem;

Exemplo: O bem permanente "teste-adição-desaparecimento" inicialmente foi cadastrado como 'localizado' em 'exposição', ao cancelar o desaparecimento n retornou a este estado.

**Comment by eduardohumberto** [comment]
Resolvido,  testar com itens da coleção Desaparecimento criados a partir da correção

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
