### ISSUE TITLE
[IBRAM] - Filtros e Busca em Bens Temporarios

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#107]
Caso 1: Ao informar nome ou parte do nome no filtro denominação da coleção bens temporário, o sistema não realização nenhuma interação. (mesmo apertando enter).

Caso 2: Ao informar um período no filtro de data de entrada no acerto o sistema não trás os registros de acordo com a data informada, tendo itens registrados nesse período. 

Caso 3: Temos na coleção dois itens "Tem 3" e "Temp 3", se pesquisar por "tem" o sistema retorna somente o "tem 3", e o "Temp 3" é exibido como sugestão mas não o retorna.

**Comment by walisonjose** [comment]
Caso 1. Resolvido.
Caso 2.  Permitiu inserir uma data no formato (00/00/0000).  O label adicionado a página para representar o filtro do tipo data está com o formato do ano errado e a data em ordem inversa.
![snip_20170727135345.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59710fdbd35e61001a4bc50f/125516c66e82c728ace21e0d46fb9a9333bdd1f9debeef14f60aa1c77c1573266b48e13b628ae92dbc56395b4d5a47ab490d5a45a9fcdc7faeb63b708a5f0ab8d86e5973c12f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78a8e483a1b031f8afc5f27ed.png)
