### ISSUE TITLE
Função de Impressão incompleta

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#11]
A Título de testes, fiz uma impressão de uma inicitaiva e só vieram poucas informações. Não sei se eu preciso configurar algumas coisa, mas o caso é que só veio pouca coisa, conforma print
![captura de tela de 2017-04-25 23-33-32](https://cloud.githubusercontent.com/assets/4163139/25415719/cca9a508-2a0f-11e7-858e-7b7a03c70aaf.png)

**Comment by juliannyasilva** [comment]
A impressão de itens em PDF esta em questionamento em relação a sua configuração.

**Comment by juliannyasilva** [comment]
Não reproduzido.
