### ISSUE TITLE
[Tainacan] Label Filtro Metadado Fixo - Página Edição Metadados

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#110]
Na tela de edição de metadados e filtros ao colocar um metadado fixo que já tenha tido o seu label editado, por exemplo o campo número de registro, que na verdade é o metadado fixo título, na listagem dos filtros o novo label não é exibido.

**Comment by juliannyasilva** [comment]
Verificado, sem inconsistências.
