### ISSUE TITLE
Nova API

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#111]
Documentando aqui a ideia inicial da nova API. Depois podemos destrinchar isso em tarefas menores.

Vamos usar o esquema da API do WordPress e a proposta é que façamos uns endpoints específicos do tainacan pra facilitar a consulta.

Em um primeiro momento, vamos nos preocupar apenas com a leitura das informações públicas. Em um segundo momento, podemos retornar as informações privadas para usuários que estiverem autenticados. Por último, podemos implementar alguns métodos de escrita.

Para essa primeira etapa, de leitura de informações públicas, pensamos nos seguintes Endpoints:

| Tipo | Endpoint | Descrição |
| -- | -- | -- |
| [GET] | collections | Lista as coleções e suas infos básicas |
| [GET] | categories | Lista todas as categorias |
| [GET] | collections/?filter... | Este método pode receber filtro para filtrar coleções |
| [GET] | collections/:id | Lista as informações de uma coleção  |
| [GET] | collections/:id/items | Lista os objetos de uma coleção |
| [GET] | collections/:id/items/?includeMetadata=1 | Lista os objetos de uma coleção com todos metadados |
| [GET] | collections/:id/items/?filter... | Possibilidade de filtrar a busca por objetos |
| [GET] | collections/:id/metadata  | Lista os metadados de uma coleção |
| [GET] | collections/:id/metadata/:id | Detalha as informações sobre um metadado |
| [GET] | repository/items | Lista os objetos de todo o repositório (pode receber filtros tb) |
| [GET] | repository/metadata | Lista todos os metadados do repositório |
| [GET] | repository | Exibe informações sobre o repositório |

Nossa principal dúvida aqui é em relação aos métodos que terminam com `metadata`:

* Eles vão listar todos os metadados, e as categorias relacionadas a eles tb?
* Fazemos uma opção de uma listagem simplificada, só com o nome, e outra completa, com tudo sobre todos os metadados, incluindo todos os valores possíveis de uma categoria, por exemplo.
* Fazemos um método só, chamado `metadata` mesmo (ou `filters`, ou `fields`)? Ou quebramos um para metadados e outro para categorias?

Resolvendo isso, acho que o trabalho pra desenvolver a API vai ser:

1. Remover o plugin atual
2. Criar os endpoints principais
3. Criar os controllers pra retornar a busca dos metadados
4. Criar uma sintaxe de filtros para buscar objetos
5. Fazer a API traduzir essa sintaxe para o que o Controller atual usa

**Comment by leogermani** [comment]
Link de referência para personalizar API do WP: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

**Comment by mbrunodm** [comment]
- [x] AutoLoad de classes
- [x] Remover Plugin atual
- [x] Criar Endpoint de Coleções
- [x] Criar Endpoint de Objetos
- [x] Criar Endpoint do Repositório
- [x] Endpoints de busca e filtros
- [x] Testar endpoints

**Comment by juliannyasilva** [comment]
Verificado e validado.
