### ISSUE TITLE
Melhorar visualização de PDF

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#112]
Hoje utilizamos o embed padrão de PDF do navegador.

Este embed não dá muitas opções de visualização, principalmente, ele não tem a opção de Tela cheia.

Precisamos pesquisar uma nova solução de visualização. Numa olhada rápida achei isso aqui que parece ser bem suportado e usado: https://mozilla.github.io/pdf.js/

**Comment by juliannyasilva** [comment]
Implementado o PDFJs!
