### ISSUE TITLE
[IBRAM] - Edição de Bem Temporário

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#114]
Inconsistência: duplicação de valores dos metadados:
![image](https://user-images.githubusercontent.com/11639242/28846278-30571a40-76e1-11e7-94c4-b70694e83b72.png)

**Comment by eduardohumberto** [comment]
Testar com itens criados recentemente

**Comment by juliannyasilva** [comment]
Verificado, sem inconsistências.
