### ISSUE TITLE
[IBRAM] Inconsistências na Entidades

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#118]
### Adição de uma Entidade
- [x] Ao criar um entidade com um nome único, e o item entidade for excluído.  Se adicionar uma nova entidade o sistema permite utilizar o nome único do item excluído. Causando assim uma duplicação de chaves, se restaurar o item antigo da lixeira. (Ex. item mig 3.) 
![image](https://user-images.githubusercontent.com/11639242/28979145-05c9b5d6-791f-11e7-8320-d4ddad6f7464.png)

### Visualização de uma Entidade
- [x] Nos metadados composto onde é possível adicionar mais de um campo, o sistema na visualização só apresenta o primeiro campo ignorando os outros. 

### Edição de uma Entidade 
- [x] Nos metadados de relacionamento na edição, se vc excluir o dado dele, e tentar adicionar um novo dado, não é apresentado na interface que o dado foi adicionado, mas se salvar as alterações, esta persistindo o novo valor. 
- [x] Nos metadados compostos onde possui mais de um campo com dados, não permite excluir tais campos, somente adicionar novos.
- [x] Não persiste os novos campos acrescentados nos metadados compostos na edição. 

### Exclusão de um item Entidade
- [x] Apresentou erro de interface apos exclusão de um item: 
![image](https://user-images.githubusercontent.com/11639242/28978711-6d5fe0a0-791d-11e7-8360-a18ca1acdc04.png)
- [x] O item "mig" foi excluído logo apos que ocorreu o erro de interface acima, e o item não consta na lixeira. Onde está o item "mig"?

### Eventos de Entidades
- [x] O item "mig" que foi excluido e não consta na lixeira, seu evento esta na aba de eventos verificados.  Mas a exclusão de outros itens não consta nessa aba, e sim em outra, na aba de eventos não verificados.  (OBS: todos os eventos de exclusão estão na aba de não verificados, menos o evento de exclusão de mig que foi pra aba de verificado.)
![image](https://user-images.githubusercontent.com/11639242/28979506-73315006-7920-11e7-98e7-c898f5f1675d.png)
![image](https://user-images.githubusercontent.com/11639242/28979520-82a88978-7920-11e7-9c2e-f8840dbe3e80.png)

Especulação: Será que apos ocorrer os erros de interface, o sistema assume os eventos próximos todos como verificado? Verificar este cenário de teste.

**Comment by juliannyasilva** [comment]
![image](https://user-images.githubusercontent.com/11639242/29081939-6ac293cc-7c3a-11e7-834d-efb11d537f5f.png)

Cenário: Adição de uma entidade, edição da entidade criada, e sua exclusão.

Inconsistência: A entidade excluída não consta na lixeira,  e permite criar uma nova entidade utilizando seu nome. 

Obs: O evento de exclusão consta como verificado, devido que a entidade houve uma edição.

**Comment by eduardohumberto** [comment]
Testar com novos itens

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
