### ISSUE TITLE
Estilo do Metadado composto

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#12]
Na busca avançada está faltando dar um estilo nos metadados compostos, conforme print abaixo: 

![estilo-categorias-juntas](https://cloud.githubusercontent.com/assets/4163139/25416150/a1b83b22-2a12-11e7-91ba-bf0ba8c5336e.png)

**Comment by Weryques** [comment]
No Firefox o bootstrap estiliza algumas coisas de forma diferente.
Veja no firefox e depois em outro navegador, irá perceber a diferença.

Portanto a estilização já existe. Se não houvesse estilização o resultado ser algo assim:
 
![ret](https://cloud.githubusercontent.com/assets/4978815/25444219/c28ce4f6-2a80-11e7-8b1d-ae36b07eeea7.png)

**Comment by juliannyasilva** [comment]
Verificado, e como o acesso ao site que foi reportado a issue esta indisponível, e não é reproduzido no tainacan, tratado como corrigido.
