### ISSUE TITLE
[IBRAM] Inconsistências em Eventos (Geral)

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#120]
### Naveção
![image](https://user-images.githubusercontent.com/11639242/28980316-bda7510a-7923-11e7-97dc-f29719678888.png)
- [x] Navegação entre os eventos desconfigurado.

### Ordenação
![image](https://user-images.githubusercontent.com/11639242/28980461-32bcbdb8-7924-11e7-996f-4418483c19c6.png)
![image](https://user-images.githubusercontent.com/11639242/28980715-47df6848-7925-11e7-97c7-a9ef6d8062a0.png)
- [x] Ordenação por data desconfigurado.
- [x] Ordenação por tipo de evento desconfigurado.

### Padrão
![image](https://user-images.githubusercontent.com/11639242/28980885-dd9ec9f0-7925-11e7-9e25-8edac703d4fc.png)
- [x] Definir um padrão de nomeclatura para funcionaldiade. Ex: Deletar ou Remover

**Comment by eduardohumberto** [comment]
Padrões de tradução devem ser estabelecidos para todo o site, deve-se aprofundar não apenas nesta tela.  Vou checar esse campo pois devemos considerar em criar uma nova issue de melhoria, especificamente para este tema.

**Comment by juliannyasilva** [comment]
Verificado!
