### ISSUE TITLE
[Tainacan] Expansão Campo Numérico - Página Visualização Item 

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#122]
Na página de visualização do item os campos de metadados numéricos não expandem o campo para edição de seus valores no momento que o usuário clica sobre o ícone. Exemplos:
  [http://www.openscreenshot.com/SJvTMNfDW](url) [http://www.openscreenshot.com/SJOFGEGvZ](url)

**Comment by eduardohumberto** [comment]
Links quebrados

**Comment by juliannyasilva** [comment]
corrigido.
