### ISSUE TITLE
[IBRAM] Inconsistências Gerais do Site

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#123]
### Inconsistências verificadas com frequência = as vezes.
- [x] Definir as permissões entre os níveis de usuários,  definindo ate que nivel (assinante, editor, etc) pode ser operado dentro do site IBRAM. 
- [x] Apresenta tela preta ao tentar acessar as categorias a partir da home do repositorio (pagina incial)  e ao tentar se registrar no site IBRAM.
![image](https://user-images.githubusercontent.com/11639242/28981700-2e701552-7929-11e7-9b1b-b2c9b189d018.png)
- [x] A coleção bem museológico esta com um destaque azul fora do padrão as outras.
- [x] Manipulando muito uma coleção ocorre erros de interface que afetam as funcionalidades executadas seguintes aos erros.
![image](https://user-images.githubusercontent.com/11639242/28981616-d732ef76-7928-11e7-980e-0ff2a90b48b2.png)
- [x] Se navegar muito entre paginas de uma coleção, ocorre travamentos fazendo com que uma pagina solicitada não seja carregada totalmente, tendo que atualizar para poder descer a pagina.

**Comment by r-guimaraes** [comment]
Até então, o usuário, ao registrar no Tainacan, possui as permissões de "assinante" do Wordpress

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
