### ISSUE TITLE
[IBRAM] Inconsistências em Coleções

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#125]
## Coleção com edição
![image](https://user-images.githubusercontent.com/11639242/28985583-9481b944-7939-11e7-87af-772f943945a9.png)
(Foram criados novos bens para esse teste: "Perm Test Mig Coleções Com Edição" e "Temp Test Mig Coleções Com Edição". E um novo conjunto: "Coleção Migração Com Edição"... Ambos foram adicionados no campo "bens" e "conjunto de bens" na adição da coleção "Coleção Migração Com Edição").

- [x] Na edição do item "Coleção Migração Com Edição" no **campo "bens"**, ao excluir o segundo bem "Temp Test Mig Coleções Com Edição", desapareceu tanto o segundo quanto o primeiro bem. Onde ao pesquisar de novo para adiciona-los são retornados. Mas ao seleciona-los nos resultados e mandar adicionar novamente os bens, não aparece na interface de edição os bens informados adicionados.

- [x] Na edição do item "Coleção Migração Com Edição" no **campo "Conjunto de bens"**, apos excluir o único conjunto informado e tentar adiciona-lo de novo. Apos pequisa-lo e mandar adicionar novamente o conjunto "Conj Mig Test Coleções", o mesmo não aparece na interface de edição o conjutno informado adicionado.

- [x] Ao salvar a coleção que teve seus dados alterados, e visualiza-la sua apresentação, é verificado valores dos metadados Bens e Conjunto de Bens duplicados.
![image](https://user-images.githubusercontent.com/11639242/28985476-1f6d837c-7939-11e7-8349-46133aea5907.png)

- [x] Ao comandar a exclusão da coleção criada no passo 3, o sistema exclui a coleção, mas a mesma não é apresentada na lixeira.

- [x] Permitiu criar uma nova coleção no passo 4, com mesmo nome da coleção editada excluída no passo 3. 

## Coleção sem edição
![image](https://user-images.githubusercontent.com/11639242/28986125-0e4432b4-793c-11e7-919c-d56335ee822d.png)
(Foram criados novos bens para esse teste: "Perm Test Mig Coleções Sem Edição" e "Temp Test Mig Coleções Sem Edição". E um novo conjunto: "Coleção Migração Sem Edição"... Ambos foram adicionados no campo "bens" e "conjunto de bens" na adição da coleção "Coleção Migração Sem Edição").

- [x] Na adição de nova coleção sem edição no campo "Bens" esta trazendo os bens relacionados com a coleção criada no teste anterior, quebrando a regra 106 da norma: 
![image](https://user-images.githubusercontent.com/11639242/28985921-33e69616-793b-11e7-9210-1d88a36d66a9.png)
![image](https://user-images.githubusercontent.com/11639242/28985938-4464a8a2-793b-11e7-9938-f8f2872cb587.png)

- [x] Na exclusão da coleção criada que não sofreu edição, apos confirmar a exclusão, o sistema recarregou a pagina, e ao terminar ocorreu um travamento na pagina, não permitindo descer na pagina de coleções. (Apos recarregar a pagina e comandar a exclusão pela segunda fez, o travamento ocorreu de novo, mas excluiu a coleção).

- [x] Permitiu criar uma nova coleção com o mesmo nome da coleção (não editada) excluída.

- [x] Na adição da terceira coleção, com o mesmo nome da coleção 2 (sem edição) trouxe no campo "Bens" os bens informados nas duas coleções anteriores.

- [x] Na adição da terceira coleção no campo "conjunto de bens" trouxe uma coleção, sendo que era pra trazer somente conjuntos. E ainda trouxe o conjunto relacionado na coleção 2, quebrando a regra 107. 
![image](https://user-images.githubusercontent.com/11639242/28986294-b7a6eec8-793c-11e7-988b-17201d2da7cd.png)
![image](https://user-images.githubusercontent.com/11639242/28986338-e5edf952-793c-11e7-94b7-beb154a54a22.png)

**Comment by eduardohumberto** [comment]
"Na adição de nova coleção sem edição no campo "Bens" esta trazendo os bens relacionados com a coleção criada no teste anterior, quebrando a regra 106 da norma"

"Na adição da terceira coleção, com o mesmo nome da coleção 2 (sem edição) trouxe no campo "Bens" os bens informados nas duas coleções anteriores."


Selecionar na configuração do metadado a opção 'Evitar itens já vinculados'

**Comment by eduardohumberto** [comment]
"Na exclusão da coleção criada que não sofreu edição, apos confirmar a exclusão, o sistema recarregou a pagina, e ao terminar ocorreu um travamento na pagina, não permitindo descer na pagina de coleções. (Apos recarregar a pagina e comandar a exclusão pela segunda fez, o travamento ocorreu de novo, mas excluiu a coleção)."

Testado  aqui [https://ibram.medialab.ufg.br/colecoes-2] e não reproduziu

**Comment by eduardohumberto** [comment]
"Na adição da terceira coleção no campo "conjunto de bens" trouxe uma coleção, sendo que era pra trazer somente conjuntos. E ainda trouxe o conjunto relacionado na coleção 2, quebrando a regra 107."

Existe uma 'coleção' criada em conjuntos

Criei uma coleção vinculada ao conjunto de moedas , ao abrir  o formulário para criar uma nova coleção o conjunto moedas já não estava presente, pois foi selecionado.  Por favor, seria interessante me mostrar o erro acontecendo.

**Comment by juliannyasilva** [comment]
## Coleção sem edição
- [x] Pensando nesse relacionamento entre os campos bens e conjuntos de bens na adição de uma coleção. Será necessário realizar um ajuste nas buscas de ambos; Pois de acordo com as regras 106 e 107, os itens vinculados a um desses campos não podem simultaneamente esta associados ao outro.
Campo "Bens":
![image](https://user-images.githubusercontent.com/11639242/29036285-3648f80e-7b75-11e7-9509-cbcfd95df7ff.png)
Campo "Conjunto de Bens": 
![image](https://user-images.githubusercontent.com/11639242/29036290-42241014-7b75-11e7-946a-be444eb617e1.png)

## Travamento na exclusão de coleção sem edição
- [x] Reprodução: Passo1: Criar uma coleção; Passo2: Comanda sua exclusão; Passo3;Tentar rolar pra baixo a tela (travamento).
Testes feitos nos navegadores: Chrome e Firefox
![image](https://user-images.githubusercontent.com/11639242/29036757-1dadc6a6-7b77-11e7-8ebb-69e6eaf93c44.png)

**Comment by juliannyasilva** [comment]
Verificado.

**Comment by juliannyasilva** [comment]
- [x] Ao excluir uma coleção que possui bens e conjuntos relacionados o sistema deveria se comportar como a coleção Conjuntos, avisando ao usuário que existe entidades relacionados a coleção e não excluir a coleção.  Mas esta permitindo excluir uma coleção, e criar outra coleção relacionando os mesmo bens e conjuntos. Onde ao restaurar a coleção excluida anteriormente, gera duplicidade de bens e conjuntos nas coleções quebrando as regras 106 e 107.

**Comment by juliannyasilva** [comment]
Verificado e validado.
