### ISSUE TITLE
[Tainacan] Capas e miniaturas de coleção - impossível trocar capa e miniatura, para depois que tento cortar e finalizar a edição da imagem

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#126]

**Comment by r-guimaraes** [comment]
Vou dar uma olhada neste caso

**Comment by leogermani** [comment]
O @andre2ar já tava vendo, fala com ele.

No meu ambiente local não consegui reproduzir. A interface tá ruim, mas funciona.

**Comment by juliannyasilva** [comment]
Ao reproduzir a adição de uma miniatura em uma coleção, apos selecionar uma imagem e cortar a mesma para salvar. O sistema trava no processamento da miniatura, não concluindo o carregamento da imagem para a miniatura. 
![image](https://user-images.githubusercontent.com/11639242/29185255-11e6c326-7ddf-11e7-9f4c-0a23503d096a.png)

**Comment by juliannyasilva** [comment]
Verificado!
