### ISSUE TITLE
Atualização das informações de um item: Quando atualizamos as informações de um item, depois da mensagem de ok, somos redirecionados para outro item

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#127]
Atualização das informações de um item: Quando atualizamos as informações de um item, depois da mensagem de ok, somos redirecionados para outro item, as vezes em outra coleção. NÃO TESTAR NO PRIMEIRO ITEM DA COLEÇÃO, MUITAS VEZES É PARA ELE QUE SOMOS REDIRECIONADOS.

**Comment by juliannyasilva** [comment]
Verificado, e corrigido.
