### ISSUE TITLE
Depois de colocar uma nova categoria em um descritor, ela demora para ficar disponível, dando a impressão que algum erro ocorreu. Precisa recarregar a página para parecer

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#129]

**Comment by andre2ar** [comment]
A requisição estava sendo bloqueada no servidor, foi desbloqueada

**Comment by leogermani** [comment]
Que requisição? bloqueada por que?

**Comment by andre2ar** [comment]
O plug-in Wordfence estava bloqueando a requisição ao property_controller.php, estava indicando uma vunerabilidade xss.

**Comment by juliannyasilva** [comment]
Verificado.
