### ISSUE TITLE
Orientação para inserção de miniatura

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#13]
É importante que no próprio cadastro de uma iniciativa seja aprsentado qual o tamanho exato da imagem para ser usada como miniatura. 
Enquanto isto, podem nos informar?

**Comment by leogermani** [comment]
- [x] colocar o domínio `tainacan` como segundo parâmetro na função `_e()`.

- [x] Atualizar o arquivo de tradução com a tradução para pt-BR

**Comment by juliannyasilva** [comment]
Ao reproduzir a adição de uma miniatura em uma coleção, apos selecionar uma imagem e cortar a mesma para salvar. O sistema trava no processamento da miniatura, não concluindo o carregamento da imagem para a miniatura. 
![image](https://user-images.githubusercontent.com/11639242/29185255-11e6c326-7ddf-11e7-9f4c-0a23503d096a.png)

**Comment by juliannyasilva** [comment]
Esta issue esta sendo contemplada e corrigida na #126, por isso esta sendo fechando.
