### ISSUE TITLE
-Metadados: quando entramos na edição do item pela página da coleção, não consigo mais encontrara a opção “outros”

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#131]
Metadados: quando entramos na edição do item pela página da coleção, não consigo mais encontrara a opção “outros” dentro do metadado “tipo”. Antes era possível criar novas categorias.  Quando entramos na edição do item pela página do item, vemos a opção outros mas sem a positividade de inserir o tipo deste novo item

**Comment by juliannyasilva** [comment]
Verificado, e esta existente a opção outro no metadado tipo.
