### ISSUE TITLE
Mobile: Ao abrir uma coleção com vários filtros no mobile, não consigo visualizar os itens

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#132]
só dá para visualizar os filtros. Não dá para mover a página, abra esta página no mobile: https://bibflora.medialab.ufg.br/guias/. A única maneira de visualizar é clicando na barra lateral direita, assim podemos sair da caixa dos filtros e visualizar o conteúdo.

**Comment by juliannyasilva** [comment]
Verificado, e corrigido.
