### ISSUE TITLE
[Tainacan] Aprovação de Eventos

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#134]
O Douglas estava revisando as mensagens dos eventos, e verificou algumas inconsistências nos eventos dos CRUDS dentro do tainacan, como podem ver na planilha: https://docs.google.com/spreadsheets/d/10E-k8dOrIboCj03nu9xcGUfSYJRWDkOKPJ801rrXabg/edit?usp=sharing

Portanto, realizar uma analise da planilhar  e tomar as correções necessárias: 

Site: http://acervos.culturadigital.br/design/tainaca-org/

**Comment by juliannyasilva** [comment]
![2](https://user-images.githubusercontent.com/11639242/29191374-e30f9108-7df3-11e7-950e-9d41d5cf368b.PNG)
![1](https://user-images.githubusercontent.com/11639242/29191375-e32985cc-7df3-11e7-839c-f3d6c0881104.PNG)

**Comment by douglasveronez** [comment]
A planilha já está atualizada com testes feitos na versão mais atualizada do tainacan.
(http://dev.medialab.ufg.br/tainacan/).

**Comment by juliannyasilva** [comment]
Testar os eventos de metadado de termo @douglasveronez  apos sua implementação em #175 .
