### ISSUE TITLE
[Tainacan] Aplicação de tema nas coleções

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#135]
Algumas funcionalidades não estão sofrendo a aplicação de um novo tema de cor como podem ver no print abaixo, de acordo com o design os icones azuis devem mudar de cor, mantendo somente os icones de cor cinza (lupa de pesquisa, etc):
## Tema
![image](https://user-images.githubusercontent.com/11639242/29191452-2135175a-7df4-11e7-97b2-afd77f244653.png)

## Coleção
![image](https://user-images.githubusercontent.com/11639242/29275066-43d32164-80e0-11e7-9edd-e5e0b54dfa96.png)

**Comment by r-guimaraes** [comment]
Estes itens circulados não foram planejados para serem alterados mesmo

**Comment by juliannyas** [comment]
De acordo com o Thayrone os ícones azuis devem mudar de cor, a lupa de pesquisa é cinza, a cor dela não altera.
