### ISSUE TITLE
[Tainacan] Formulário de registro de novos usuários

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#137]
No formulário de registro de novos usuários  no sistema possui o link "Mais opções" que apresenta mais campos (Sobre você, Local de trabalho atual e resumo profisisonal). A melhoria seria utilizar os valores destes campos se informados dentro do sistema, ou excluir tais campos do formulario. 

Cenário: Criei o usuário 'user' no sistema informando valores nestes campos, e não foi possível visualizar tais informações dentro do sistema, e nem no painel de usuários no admin Wordpress.

**Comment by eduardohumberto** [comment]
A partir de agora essa informação poderá ser visualizada no perfil do usuário

**Comment by juliannyasilva** [comment]
Verificado!
