### ISSUE TITLE
[Tainacan]Metadado de Texto Longo não reconhece formatação

### ISSUE THREAD

**Issue by eduardo2s** [medialab-ufg/tainacan#138]
Quando se usa quebra de linha por exemplo, para se escrever um índice ou texto o metadado de texto longo não identifica isso e coloca todo texto junto como se fosse um único paragrafo.

**Comment by juliannyasilva** [comment]
- [ ] Retorno 1: Tratar nas telas de adição e visualização de item com enfase no metadado uma formatação inserida manualmente ou colada nos campos de metadado de texto longo.
- [ ] Retorno 2: Tratar nas telas de adição e visualização de item com enfase na mídia uma formatação inserida manualmente ou colada nos campos de metadado de texto longo.

**Comment by juliannyasilva** [comment]
Verificado.
