### ISSUE TITLE
[IBRAM] Adição/Edição/Visualização de Bens Permanente e Temporário

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#139]
OBS: Os itens marcados como melhoria, poderão ser deixados para um futuro momento.

- [x] Busca de entidades em campos/metadados de relacionamento ao ser digitado parte do nome (palavra chave), o sistema deverá exibir, em uma lista de opções, o campo “Nome” dos registros de “Entidades” de qualquer tipo cujo nome **e/ou outros nomes**  possuam parte do texto digitado e **no mínimo a função desejada** (Ex: avaliador, ator/coator, seguradora, etc).

- [x]  Ao solicitar a inclusão de mais um item, o botão de incluir outro está desaparecendo. Caso o usuário não forneça informação para o campo e solicite a sua exclusão (x), o botão para inclusão não é mais exibido sendo necessário retornar a tela de pesquisa e entrar novamente nas informações do item. Esse comportamento foi identificado para o campo "Outros números" e pode ser que se repita nos campos Autores, Resumo Descritivo, Referências Bibliográficas, Características físicas e  Marcações/Inscrições.

- [x] Na tela de edição do item nos metadados: Características físicas, Modo de Aquisição, Valor estimado, Seguro. As informações para o metadado 'Valor' não estão sendo recuperadas. 

- [x] Os números informados no campo 'outros números' devem ser validados entre si, ou seja,  pode ser informado vários outros números, porém não podem ser idênticos entre si. (A verificação é feito entre si na adição de um bem, mas varios bens podem ter o mesmos valores do metadado 'outros numeros'.)

- [ ] (Melhoria solicitada pelo IBRAM) Nos eventos ocorridos dentro das coleções bens informar no pop-up de evento realizado com sucesso,  o numero de registro do bem que sofreu o evento.

- [x] Metadado 'Data final' do metadado composto Seguro, deve ser renomeado para 'Data fim'.

- [x] O campo deve permitir a inserção de mais de um autor porém, para cada autor inserido deverá ser informada sua função. Ou seja, cada autor desempenha função e nesse caso deverá existir apenas um autor por função. O sistema permite informar mais de um autor por função.

- [x] A pesquisa no metadado 'Coleção' na adição de um Bem não está retornando as coleções que não possuem bens vinculados o que é errado, deveria retornar todas as coleções ativas no repo, pois um Bem não **pode estar em mais de um conjunto ou coleção**, porém uma coleção ou conjunto pode **possuir 1 ou vários Bens associado**.

- [x] Label do critério de pesquisa (palavra chave) deverá ser unificado para todos os componentes de busca na formulário de adição e edição de bens. Renomear todos os labels dos metadados de busca para 'palavra chave' caso não esteja nesse padrão.

- [x] No metadado Autoria > Atribuida > Autor, está marcando a função detentor do direito e ao excluir este relacionamento, o sistema recupera automaticamente tal termo. Retirar o termo detentor de direito no metadado autor.

**Comment by eduardohumberto** [comment]
'Ao solicitar a inclusão de mais um item, o botão de incluir outro está desaparecendo. Caso o usuário não forneça informação para o campo e solicite a sua exclusão (x), o botão para inclusão não é mais exibido sendo necessário retornar a tela de pesquisa e entrar novamente nas informações do item. Esse comportamento foi identificado para o campo "Outros números" e pode ser que se repita nos campos Autores, Resumo Descritivo, Referências Bibliográficas, Características físicas e Marcações/Inscrições.'

O botão aparece ao preencher o campo e ao excluir o botão será mostrado

**Comment by eduardohumberto** [comment]
"Metadado 'Data final' do metadado composto Seguro, deve ser renomeado para 'Data fim'."

Configuração do metadado

**Comment by eduardohumberto** [comment]
"O campo deve permitir a inserção de mais de um autor porém, para cada autor inserido deverá ser informada sua função. Ou seja, cada autor desempenha função e nesse caso deverá existir apenas um autor por função. O sistema permite informar mais de um autor por função."

Ir na categoria Atribuída ( Autoria > Atribuída ),  editar, selecionar metadados, editar metadado autor, selecionar o campo valor único.

**Comment by eduardohumberto** [comment]
"Busca de entidades em campos/metadados de relacionamento ao ser digitado parte do nome (palavra chave), o sistema deverá exibir, em uma lista de opções, o campo “Nome” dos registros de “Entidades” de qualquer tipo cujo nome e/ou outros nomes possuam parte do texto digitado e no mínimo a função desejada (Ex: avaliador, ator/coator, seguradora, etc)."

Este é um ponto complicado para se mexer porém resolvi,, colocado a busca textual na busca central, desta forma ele vai encontrar o titulo do metadado, nos demais metadados

**Comment by eduardohumberto** [comment]
A pesquisa no metadado 'Coleção' na adição de um Bem não está retornando as coleções que não possuem bens vinculados o que é errado, deveria retornar todas as coleções ativas no repo, pois um Bem não pode estar em mais de um conjunto ou coleção, porém uma coleção ou conjunto pode possuir 1 ou vários Bens associado.

Bastava retirar a opção 'Buscar itens vinculados', já realizado

**Comment by eduardohumberto** [comment]
No metadado Autoria > Atribuida > Autor, está marcando a função detentor do direito e ao excluir este relacionamento, o sistema recupera automaticamente tal termo. Retirar o termo detentor de direito no metadado autor.

Corrigido na branch  tainacan pages, por enquanto evitar de abrir a página de categorias pela página inicial

**Comment by juliannyasilva** [comment]
Verificado, e ok.

**Comment by juliannyasilva** [comment]
- [x] Busca de entidades em campos/metadados de relacionamento ao ser digitado parte do nome (palavra chave), o sistema deverá exibir, em uma lista de opções, o campo “Nome” dos registros de “**Entidades**” de qualquer tipo cujo **nome e/ou outros nomes** possuam parte do texto digitado e no mínimo a função desejada (Ex: avaliador, ator/coator, seguradora, etc).

Foi realizado a configuração do metadado "outros nomes" em entidades, trazendo para fora do metadado de categoria "tipo de entidade". Logo, falta definir nos metadados de relacionamento como irá olhar para o campo "outros nomes" , e trazer resultados inserindo tais nomes.

- [x] Campo custódio em bem temporário não esta apresentando mais o campo "Proprietário" que é um metadado de relacionamento. E o mesmo esta inserido na categoria da coleção em "campo custodia - bem permanente".

**Comment by eduardohumberto** [comment]
"Busca de entidades em campos/metadados de relacionamento ao ser digitado parte do nome (palavra chave), o sistema deverá exibir, em uma lista de opções, o campo “Nome” dos registros de “Entidades” de qualquer tipo cujo nome e/ou outros nomes possuam parte do texto digitado e no mínimo a função desejada (Ex: avaliador, ator/coator, seguradora, etc)."

Solicitar a atualização do plugin e do core do tainacan

**Comment by juliannyas** [comment]
## Bem temporário
- Campo Proprietário dentro de custódia: não esta filtrando de acordo com o esperado.
- Durante os testes de funções a edição das funções nas entidades gerou a seguinte duplicação:
![image](https://user-images.githubusercontent.com/11639242/30037280-d09a6250-918f-11e7-9452-e9dc960d26f7.png)

## Bem permanente
- Campo Proprietário Anterior nas varias opções de Modo de aquisição: não esta filtrando de acordo com o esperado.

**Comment by juliannyasilva** [comment]
Validado.
