### ISSUE TITLE
Tamanho de texto muito longo

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#14]
Temos um metadado de texto para inserção de URLs e acabamos de nos deparar com uma URL muito grande que acaba quebrando na página, ver aqui: http://medialab.ufg.br/democraciadigital/iniciativas/al%C3%B4-senado-online

**Comment by jpmehl** [comment]
Percebi agora que o linque não está funcionando tb.

**Comment by juliannyasilva** [comment]
Verificado, e erro não reproduzido, considerado como corrigido.
