### ISSUE TITLE
[Tainacan] Adição / Edição de Item

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#141]
- [x] Não permite adicionar mais de um valor no metadado marcado como Múltiplos valores.

- [x] Não permite remover um campo adicionado em metadado marcado como Múltiplos valores.
![image](https://user-images.githubusercontent.com/11639242/29331567-40f88f62-81d3-11e7-979c-dd04ee608c46.png)

- [x] Metadados criados pelo usuário não estão sendo apresentados quando o layout configurado em enfase na mídia.

**Comment by eduardohumberto** [comment]
Metadados so podem ser adicionados se vc preencher o campo

**Comment by juliannyasilva** [comment]
Verificado, e corrigido.
