### ISSUE TITLE
[IBRAM] Coleção Entidade

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#144]
- [x] Na adição de uma entidade do tipo 'pessoa', inserir a opção de permitir data aproximada na data de nascimento. 

- [x] Na adição de uma entidade do tipo 'pessoa', retirar  a duplicação no aviso de existência de um CPF/CNPJ.

- [x] No log de eventos da coleção entidade, renomear o evento de edição de entidade de Criar item -> Editar Item, pois hoje no log de eventos não possui diferença entre criar e editar entidade.

- [x] Na adição de uma entidade do tipo 'pessoa' e 'entidade coletiva' padronizar os campos "pais" e "estado/provincia/cidade", retirar o contorno pontilhado do campo e deixar linha, e deixar a entidade coletiva como a entidade pessoa na seleção do país. 

- [x] No metadado CPF deve existir uma verificação, verificar na adição e **edição** de uma entidade se o valor do metadado CPF e CNPJ já existe no sistema, e não permitir duplicar o valor no sistema. 

- [x] Na restauração de uma entidade da lixeira, realizar uma verificação não permitindo restaurar uma entidade no qual os valores dos metadados nome, tipo de  entidade e cpf/cnpj, se já existir uma entidade ativa com os mesmo valores. Para não gerar duplicidade.

**Comment by eduardohumberto** [comment]
O primeiro item é configurado no próprio metadado

**Comment by eduardohumberto** [comment]
"No log de eventos da coleção entidade, renomear o evento de edição de entidade de Criar item -> Editar Item, pois hoje no log de eventos não possui diferença entre criar e editar entidade."

O tainacan não existe o log do evento editar item ( isto vem desde o inicio) , somente é 'logado' o criar,  a duplicação do criar item é um log errado se ocorrer deve ser analisado.

Se caso for exigido a implementação deste log, deverá ser uma nova feature

**Comment by eduardohumberto** [comment]
"Na adição de uma entidade do tipo 'pessoa' e 'entidade coletiva' padronizar os campos "pais" e "estado/provincia/cidade", retirar o contorno pontilhado do campo e deixar linha, e deixar a entidade coletiva como a entidade pessoa na seleção do país."

Configurar o metadado país da categoria 'entidade coletiva' semelhante ao da categoria 'pessoa'

A linha pontilhada será colocado como linha

**Comment by eduardohumberto** [comment]
"No metadado CPF deve existir uma verificação, verificar na adição e edição de uma entidade se o valor do metadado CPF e CNPJ já existe no sistema, e não permitir duplicar o valor no sistema.'

A validação é feita tanto para cpf quanto para cnpj, o sistema permite salvar porém é mostrado a mensagem do valor já existente e o mesmo não é persisitido, para o bloqueio do campo inválido tanto no salvar tanto no editar deve se colocar o metadado como obrigatório em sua configuração.

Sempre verificar se o valor foi duplicado na visualização do item.

**Comment by juliannyasilva** [comment]
- [x] Retorno 1: Campo CPF da entidade tipo Pessoa não esta validando valores existente.

- [x] Retorno 2: Criei e entidade 08, realizei uma alteração nela, fiz sua exclusão, e exclui permanentemente da lixeira. E ao tentar adicionar uma entidade com mesmo nome o sistema aponta nome já existente. 

- [x] Retorno 3: Ao adicionar uma cidade a uma entidade coletiva, na alteração da entidade o sistema não esta retornado no treeview a cidade selecionada. Na seleção de uma cidade deveria marcar também o estado para fins de facilitar a identificação da cidade selecionada.

**Comment by juliannyasilva** [comment]
Retorno: Apos excluir a "Entidade 00" (Esta na lixeira), e tentar adicionar uma nova entidade com mesmo nome , o sistema não esta apontando a chave existente. Antes verificada itens da lixeira, foi retirado esta verificação da lixeira em entidades?

**Comment by juliannyasilva** [comment]
Retorno: Esta permitindo a duplicação de chaves na coleção Entidades.
![image](https://user-images.githubusercontent.com/11639242/29522942-8a439c38-8661-11e7-9309-c463eacf35a0.png)

**Comment by juliannyasilva** [comment]
Retestar ao atualizar o plugin do IBRAM

**Comment by juliannyasilva** [comment]
Verificado apos atualização, e foi corrigido.

**Comment by juliannyasilva** [comment]
Retorno: Apos excluir uma entidade, e tentar adicionar uma nova entidade com mesmo CPF e/ou CNPJ. O sistema não esta verificando e validando que a chave é existente (Não mostra o alerta).

**Comment by eduardohumberto** [comment]
A mensagem está em inglês mas em breve todas serão traduzidas
