### ISSUE TITLE
[Tainacan] Busca princial na home do repositorio

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#147]
Descrição do erro 1: [Gravação 1](https://www.dropbox.com/s/in950jn5j6v0v2m/Gravar%20%235.mp4?dl=0)
Descrição do erro 2: [Gravação 2](https://drive.google.com/file/d/0B3Y7QqQ4H6oVYTI0R214dEtTOUk/view)

Como podemos ver nas gravações a busca principal não está com o comportamento esperado quando se pesquisa o nome de uma coleção do sistema. Ao que tudo indica é que a busca só esta olhando para o item, e não para coleção e item.

**Comment by juliannyas** [comment]
Retorno: Como podemos ver na [Gravação](https://drive.google.com/file/d/0B3Y7QqQ4H6oVYTI0R214dEtTOUk/view) a busca principal não está com o comportamento esperado quando se pesquisa o nome de uma coleção do sistema. Ao que tudo indica é que a busca só esta olhando para o item, e não para coleção e item.

**Comment by juliannyasilva** [comment]
Verificado, e corrigido.

**Comment by leogermani** [comment]
Não está funcionando no bibflora, por isso reabri

**Comment by leogermani** [comment]
também não está funcionando no museu do Indio

**Comment by andre2ar** [comment]
Foi necessário desativar e ativar o tema
