### ISSUE TITLE
[IBRAM] Data aproximada - Colchetes

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#148]
Ao selecionar a opção data aproximada e inserir o seu valor. Deve existe na mascara dos tipos de datas um colchete abrindo e fechando tais datas. Ex: ac. 123 - > **[** ac. 123 **]**. E apresentar os colchetes na visualização dessas datas em qualquer coleção que utilize este recurso de data aproximada.

**Comment by juliannyasilva** [comment]
Verificado.

**Comment by juliannyasilva** [comment]
A máscara não valida se todas as informações foram fornecidas.

Exemplo: [1971 ou 1972] consigo digitar apenas [1971 ou].

**Comment by eduardohumberto** [comment]
Atualizar plugin de data aproximada nas instalações

**Comment by juliannyasilva** [comment]
Verificado e validado.
