### ISSUE TITLE
[IBRAM] Estados/Cidades - Entidade Pessoa e Coletiva

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#149]
Erro: Hoje existe somente um 'País', portanto ok do campo 'Estado' ser pre carregado. Mas pensando na inclusão de um novo pais, o campo 'Estado' estado não seria atualizado. E quando selecionados um 'Estado/Provincia/Cidade' o sistema não recupera a categoria filho de Estado. 

Correção: Ao selecionar um valor para o metadado "País" automaticamente recarregar os valores do selectbox do metadado "Estado". E consequentemente ao selecionar um valor para o metadado "Estado", automaticamente recarregar os valores do selectbox do metadado "Cidade". 

- [x] Na visualização da Entidade recuperar os valores selecionados no metadados Estado e Cidade corretamente.
- [x] Na edição da Entidade recuperar os valores selecionados nos metadados Estado e Cidade corretamente, atentando para o fato de que ao alterar o estado os valores do metadado Cidade deve ser automaticamente recarregados de acordo com as cidades pertencentes ao estado selecionado. 
- [x] Nas categorias do usuário admin existe 3 categorias para Estados/Provincia/Cidades. Deletar as duas categorias não usadas, e deixar somente a que será padrão para o site. 
- [x] Atualizar a categoria de usuario padrão para Estados/Provincias/Cidades e complementar os estados e cidades que estão faltando atualmente.

**Comment by eduardohumberto** [comment]
Basta atualizar o metadado cidade para selectbox tanto em entidade coletiva e pessoa.  Estado tb precisam ser selectbox. Deve manter os estados pré carregados, e países pode ser qualquer widget pois não influencia nos demais campos

**Comment by eduardohumberto** [comment]
O plugin do ibram deve ser atualizado

**Comment by juliannyasilva** [comment]
Verificado.
