### ISSUE TITLE
[IBRAM] Validação de "Outros Números" e "Outros Nomes"

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#150]
- [x] Item 1: No cadastro de bens atualmente existe o metadado "Outros números", que permite adicionar outros números a um bem. Mas não existe uma validação entre esses números, permitindo então que seja informado valores duplicados. Pensando que a busca de bens utilizara este metadado para filtrar bens. Implementar a validação no metadado "Outros Números".

- [x] Item 2: No cadastro de entidades atualmente existe o metadado "Outros nomes", que permite adicionar outros nomes a uma entidade. Mas não existe uma validação entre esses nomes, permitindo então que seja informado nomes duplicados. Pensando que a buscas de entidades utilizara este metadado para filtrar entidades. Implementar a validação no metadado "Outros Nomes".

**Comment by eduardohumberto** [comment]
Para validação de campos Outros nomes no cadastro de entidades deve se retirar o metadado de dentro do composto , o qual faz parte.

**Comment by juliannyasilva** [comment]
Melhoria: Traduzir a mensagem de valores iguais nos campos "Outros nomes" e "Outros numeros" para português;

**Comment by juliannyasilva** [comment]
Verificado, e ok.
