### ISSUE TITLE
[IBRAM] Autocomplete nos metadados de relacionamento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#151]
Ao inserir parte de um nome de um item o autocomplete apresenta resultados não disponíveis e duplicados (Ex: campo bens em Conjuntos). A correção seria trazer no autocomplete só resultados que se clicar em "Pesquisar" serão retornados e retirar a duplicação.

**Comment by juliannyasilva** [comment]
Verificado, e ok.

**Comment by juliannyasilva** [comment]
Retorno: https://drive.google.com/file/d/0B3Y7QqQ4H6oVZ2xYT245d2xDcGM/view

- [x] Como podemos ver no video, o autocomplete para os campos de busca de localização nos bens não está apresentando no autocomplete os resultados corretamente. Ao possuir registros com parte do nome 'Loca' o sistema não sugeri no autocomplete tais registros.

- [x] Ao informar o valor "0" (zero) no campo de busca o sistema não realizar o filtro dos registros corretamente, trazendo itens como 'vitrine 44' que não possui o valor 0 em seu nome. (Obs: para outros numeros alem de 0, o filtro esta agindo normalmente).

- [x] Os metadados de relacionamento esta ativando o autocompletar com 2 letras, e o label diz que ativa com 3. Alterar nos metadados de relacionamento que busca por localização para a seguinte descrição: "Digite as 2 primeiras letras pelo menos, para ativar o autocompletar."

**Comment by eduardohumberto** [comment]
"Digite as 2 primeiras letras pelo menos, para ativar o autocompletar." Estará  em inglês inicialmente mas será traduzido após o arquivo de línguas for liberado

**Comment by juliannyasilva** [comment]
Retorno: Não apresentação de entidades resultantes em Descarte, ao informar 2 letras pelo menos no autocomplete.
