### ISSUE TITLE
[Tainacan] Alteração da foto de perfil 

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#156]
- O sistema não permite alterar a foto de perfil do usuário. 
- Não foi identificado no sistema a usabilidade desta funcionalidade.
- Definir se irá manter a utilização de fotos de usuário, e se sim, implementar usabilidade para esta funcionalidade.

**Comment by leogermani** [comment]
por agora vamos ocultar essa funcionalidade

**Comment by juliannyasilva** [comment]
Verificado e validado.
