### ISSUE TITLE
[Tainacan] Refatoração da interface "Minhas Categorias"

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#159]
**- Refatorar a interface de operação das categorias do sistema, deixando mais claro o fluxo dentro da funcionalidade, melhorando os seguintes aspectos:**
- [x] Renomear o campo "Privacidade das categorias" para **"Privacidade da Categoria"**. Pois dá a impressão de privacidade de todas as categorias e não da que esta em edição.
- [x] Renomear o campo "Moderadores das categorias" para **"Moderadores da Categoria"**. Mesmo caso de cima.
- [x] Trocar a ordem dos botões "Enviar" e "Novo".
- [x] Renomear o campo "Enviar" para "Salvar".
- [x] Renomear o campo "Novo" para "Limpar".
- [x] Ao selecionar uma categoria para edição, ao tentar selecionar outra categoria sem salvar as edições da atual. Avisar o usuário que existe alterações feitas, se realmente o usuário deseja sair da edição da categoria atual.
- [x] Renomear a categoria raiz coleção para "Categorias de **C**oleção".

**- Nos metadados de uma categoria:**
- [x] Renomear o botão "Metadados da Categoria" para **"Ver Metadados da Categoria".**
- [x] Diminuir o tamanho do botão de adição de metadados, para o tamanho do botão de ver os metadados.
- [x] Ao salvar as alterações em metadados de uma categoria, exibir um pop-up informando o usuário que as alterações foram salvas com sucesso.
- [x] Refatorar a mensagem exibida ao salvar um metadado de uma categoria: https://drive.google.com/file/d/0B3Y7QqQ4H6oVTGNNNHRkRF9DRXc/view
- [x] Hoje se somente salvar os metadados e não salvar a categoria de novo, as alterações nos metadados não são persistidos. Logo ao salvar os metadados mas tentar sair da categoria sem salva-la. Avisar o usuário num pop-up que precisa salvar a categoria para aplicar as alterações em seus metadados.
- [x] Ao clicar em "Salvar" na categoria selecionada, manter na interface da categoria. Não redirecionar para a tela inicial de manuseio das categorias. 

**- Erro de interface:**
- [x] Corrigir a fixação das opções de uma categoria da tela e deixá-las com aparência de menu (tirar transparência):
![image](https://user-images.githubusercontent.com/11639242/29583503-b81f4396-8756-11e7-9d33-ca41ce739df6.png)
- [x] Tornar responsivo a margem dos botões de salvar e limpar com a margem da div dos metadados:
![image](https://user-images.githubusercontent.com/11639242/30710934-76a3c1fa-9edd-11e7-9fce-75f50bd51bcd.png)

**Comment by juliannyas** [comment]
- [ ] Renomear o campo "Moderadores da Categoria" para "Moderadores da **c**ategoria". Deixar padronizado "categoria" com 'c' minusculo.

- [ ] A edição de categorias não esta disponível.

**Comment by juliannyasilva** [comment]
Retorno:

- [x] Ao adicionar um metadado em uma categoria, e emitido uma mensagem errônea. Deixar mais explicito o evento realizado. A correção seria mudar a msg para "O metadado foi adicionado com sucesso."
![image](https://user-images.githubusercontent.com/11639242/31089731-8514ca26-a77b-11e7-921f-1a19b3114557.png)

**Comment by juliannyasilva** [comment]
Verificado e validado.
