### ISSUE TITLE
Aprovação em moderação

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#16]
Selecionei a necessidade de moderação na coleção Ferramentas, em http://medialab.ufg.br/democraciadigital/ferramentas/admin/configuracao , sendo que ao receber a notificação de que foi feita uma alteração, deveria aparecer em qual item e em qual metadado está sendo proposta a alteração, no entanto, só aparece o item e o que foi alterado, mas não o metdado.
Seria legal se viesse cada um separdo, tido: 

Ïtem alterado: XXX
Metadado: XXX
Tido de alteração: xxx
Alteração: xxx 
 
![captura de tela de 2017-05-08 17-47-39](https://cloud.githubusercontent.com/assets/4163139/25824706/bf39d396-3416-11e7-92ab-a24f5b62d0b3.png)

**Comment by leogermani** [comment]
@andre2ar consegue referenciar aqui os commits que vc fez relacionados a essa issue?

**Comment by juliannyasilva** [comment]
Verificado, a moderação de alterações por usuários em coleções/itens que não os criadores de tais é realizado, existe uma descrição em relação qual item foi alterado, qual a alteração e em qual metadado. Mas realmente exige uma melhoria nessa questão de como os eventos são apresentados.

**Comment by juliannyasilva** [comment]
Sera discutido o comportamento dos eventos dentro do sistema, e posteriormente tratar esta questão.
