### ISSUE TITLE
[IBRAM] Remover "Sim" ou "Não" nos Metadados "Coleções" e "Conjuntos" de Bens

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#160]
Para fins de facilitar o relacionamento entre os metadados coleções e conjuntos com outras coleções do repositório, bem como deixar mais explicito o que esta ou não relacionado. Retirar o selectbox nos metadados de relacionamentos de Bens Permanente e Temporário, deixando somente como um metadado de relacionado simples.

**Comment by juliannyasilva** [comment]
Verificado, e ok.

**Comment by juliannyasilva** [comment]
![image](https://user-images.githubusercontent.com/11639242/29789111-5f2c9cf2-8c0b-11e7-8b54-f4b19c7877c6.png)
Como podemos ver na imagem acima, ao relacionar um bem na coleção Conjuntos, e visualizar este bem os dois metadados coleções e conjuntos estão sendo mostrado fora da ordem e não esta relacionando no metadado conjuntos de bens o conjunto vinculado a ele.

**Comment by eduardohumberto** [comment]
![print bem permanente](https://user-images.githubusercontent.com/4702650/29822907-6a41b1f2-8ca3-11e7-8fe4-adcbca3c6198.png)

Como mostra a imagem, ordenei os metadados nas configurações e os valores estão aparecendo tanto quando você adiciona o conjunto em Bens Permanentes tanto quanto você adiciona o Bem em Conjuntos.

**Comment by juliannyasilva** [comment]
Verificado e validado.

**Comment by juliannyasilva** [comment]
Retorno: Aplicar toda a correção dos metadados "Conjuntos" e "Coleção" no **Bem Temporário**.

**Comment by eduardohumberto** [comment]
Era apenas criar os metadados de relacionamento e remover os antigos no próprio tainacan, já feito

**Comment by eduardohumberto** [comment]
Metadados foram criados em coleções e conjuntos, verificar se o comportamento de relacionamento inverso esta ok

**Comment by juliannyasilva** [comment]
Validado.
