### ISSUE TITLE
[IBRAM] Remover opções que não serão entregues agora

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#166]
Em Desaparecimentos e Descartes, nos bens envolvidos, remover os Bens arquivisticos e bens bibliotecarios

**Comment by juliannyasilva** [comment]
Só para fins de ocultar da interface e realizar a entrega ao IBRAM  sem saber se precisa de alteração no código, deletei os metadados da coleção pois não tinha a opção de ocultar.

**Comment by juliannyasilva** [comment]
Concluido a remoção das bens arq e e biblio.
