### ISSUE TITLE
[IBRAM] Busca por funções - Metadados de relacionamento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#171]
Ao alterar uma entidade e retirar funções como avaliador, detentor do direito, seguradora, etc. O metadados de relacionamentos que buscam por funções não reconhecem que tal função não é mais exercida por uma entidade, e continua trazendo o item entidade que não possui mais tais funções.

**Comment by eduardohumberto** [comment]
em quais metadados não esta sendo reconhecido?

**Comment by juliannyasilva** [comment]
## Bem Temporário
- [x] Campo **Proprietário** do metadado de categoria "Custódia" em bem temporário, não esta sendo mostrado em 'minhas categorias' e esta realizando a busca incorreta, pois é pra trazer todas as entidades, sem distinção entre as funções.
![image](https://user-images.githubusercontent.com/11639242/30081353-37be02a2-925d-11e7-89cd-77cba55d93a1.png)

**Comment by eduardohumberto** [comment]
@juliannyas  Lembro que você falou que ia verificar este caso, pois testei e esta de acordo com as categorias selecionadas

**Comment by juliannyasilva** [comment]
Validado.
