### ISSUE TITLE
[IBRAM] Label do critério de pesquisa (palavra chave) deverá ser unificado para todos os componentes de busca

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#172]
- [x] Label do critério de pesquisa (palavra chave) deverá ser unificado para todos os componentes de busca. No qual o padrão será o nome do metadado buscado, ou seja, renomear todos os labels dos metadados de busca de 'palavra chave' para 'nome do metadado buscado'.

**Comment by eduardohumberto** [comment]
Para as alterações ficarem corretas deve-se selecionar  em todos os metadados que utiliza alguma 'entidade' o metadado Nome e Outro Nome

**Comment by juliannyasilva** [comment]
## Retorno: Metadados que ainda precisam ser renomeados suas labels e/ou incluir campo 'outros nomes':
### Descarte
- [x] Metadado **Responsável**: renomear label 'palavra chave' e incluir campo 'outros nomes'.
- [x] Metadado **Destinatário**: renomear label 'palavra chave' e incluir campo 'outros nomes'.

### Bem temporário
- [x] Metadado **Localização de guarda**, aba Administrativo: **renomear label 'palavra chave'.**
- [x] Metadado **Localização atual**, aba Administrativo: **renomear label 'palavra chave'.**
- [x] Metadado **Avaliador**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Seguradora**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Detentor de direito**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Proprietário**, aba Identificação: **incluir campo 'outros nomes'.**
- [x] Metadado **Local de produção**, aba Identificação: **renomear label 'palavra chave'.**

### Bem permanente
- [x] Metadado **Localização de guarda**, aba Administrativo: **renomear label 'palavra chave'.**
- [x] Metadado **Localização atual**, aba Administrativo: **renomear label 'palavra chave'.**
- [x] Metadado **Avaliador**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Seguradora**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Detentor de direito**, aba Administrativo: **incluir campo 'outros nomes'.**
- [x] Metadado **Proprietário anterior**, aba Identificação: **incluir campo 'outros nomes'.**
- [x] Metadado **Local de produção**, aba Identificação: **renomear label 'palavra chave'.**

**Comment by eduardohumberto** [comment]
Os metadados relacionados a coleção localização em vez de 'palavra chave' será 'localização'

**Comment by juliannyasilva** [comment]
Verificado e validado.
