### ISSUE TITLE
[IBRAM] Inclusão de mais um item em metadado multi valorado

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#182]
Cenário dos testes: https://drive.google.com/file/d/0B3Y7QqQ4H6oVYWk3d3FkYVFvbk0/view

Como podemos ver no vídeo acima existem dois comportamentos para campos multi valorados... O primeiro é o caso de 'outros numeros' e 'historico'. Onde permite a primeiro momento adicionar um campo, mas no terceiro ja obriga preencher um campo, e mesm assim permite campo em branco.
O segundo caso é o campo 'referencias bibliograficas' que não oculto o botão de adição de item.

Neste caso, o cliente do site estão questionado o porque de possuírem comportamentos diferentes. Neste caso creio que deixar todos os campos de multi valores com o padrão do segundo caso é o mais sensato. (Mesmo tendo o campo 'outros numeros' sendo um metadado utilizado por buscas de bens).

**Comment by eduardohumberto** [comment]
'referencias bibliograficas' é um metadado composto,  ou seja todos os tipos de metadados podem ser utilizados, há casos que um dos compostos são obrigatórios e outros não,  e ainda sim ser cardinalidade múltipla, podendo adicionar outro conjunto de campos mesmo com alguns campos em branco. Isto impossibilita o mesmo comportamento. 

Os demais metadados são todos texto, foi feita a correção necessária para bloquear novos campos se os demais estiverem vazios

**Comment by juliannyasilva** [comment]
Verificado e Validado.
