### ISSUE TITLE
Compartilhamento facebook

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#185]
[BRANCH pages] Ao clicaar no botão de compartilhar para o facebook de um item, a URL do item está indo em outro formato (a url da coleção) e não está exibindo certo no facebook. Modificar para ir a url da single do item conforme padrão da branch pages

**Comment by juliannyasilva** [comment]
Retorno 1: Aplicar correções no compartilhamento do item na home coleção, no botão compartilhar. https://drive.google.com/file/d/0B3Y7QqQ4H6oVbWpYdGtvSXJZSkk/view 
![image](https://user-images.githubusercontent.com/11639242/30710194-28fae48a-9edb-11e7-9e80-b734b574be77.png)
Retorno 2: Aplicar correções no compartilhamento do item na home do item, no botão compartilhar.
![image](https://user-images.githubusercontent.com/11639242/30710209-36ba7c3e-9edb-11e7-8170-dbdb260b2e14.png)

**Comment by juliannyasilva** [comment]
Verificado e validado.

**Comment by juliannyasilva** [comment]
Corrigir o compartilhamento de itens no facebook pois não esta carregando a miniatura da coleção/item.

**Comment by andre2ar** [comment]
A miniatura do item somente não será carregada caso a imagem tenha dimensões menores que 200 por 200 pixels. Caso alguma das dimensões seja menor, 278x170 por exemplo, então a imagem não será capturada.

**Comment by juliannyasilva** [comment]
No caso do pdf é a ferramenta de indexação que cria a miniatura do item, logo hoje esta ferramenta esta criando o padrão 200x200?

Padronizar o compartilhamento nos varios botões de compartilhamento, é observado que somente o compartilhar na home do item compartilha a miniatura, os compartilha que estao na engrenagem de configurações do item não.
