### ISSUE TITLE
Atualizar inserção de itens via Redes Sociais

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#189]
Atualizar integração com redes sociais para inserção de itens. 

Definir quais

Ocultar os demais que sabemos que não funciona

- [x] Youtube
- [x] Flickr
- [x] Vimeo
- [x] URL
- [x] File

**Comment by juliannyasilva** [comment]
Verificado e validado. Retirando inserção via facebook e instagram.
