### ISSUE TITLE
Fazer opção para a exibição do "Veja mais" nos filtros

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#190]

**Comment by juliannyasilva** [comment]
Traduzir a frase para PT-BR.
![image](https://user-images.githubusercontent.com/11639242/31091015-f8243516-a77f-11e7-9e15-efbf61c29d1a.png)

**Comment by leogermani** [comment]
aproveita e muda a versão em inglês para "Enable 'display more' option"

**Comment by juliannyasilva** [comment]
Verificado e validado.

**Comment by leogermani** [comment]
Está muito difícil com o texto atual de entender o que isso faz. Vamos melhorar o texto:

ingles: 
Display: [ ] For big lists, hide values and display a "see more" button

portugues:
Exibição: [ ] Para listas muito grandes, ocultar itens e exibir botão para "ver mais"

**Comment by juliannyasilva** [comment]
https://drive.google.com/file/d/0B3Y7QqQ4H6oVaXZOZk56VUE1eTQ/view

Como podemos ver ao tentar desativar o "vaja mais" no metadado fixo 'Titulo', o mesmo foi duplicado na faceta de filtros, e criado um evento para o adm da coleção (no caso eu mesma), falando que estava ocorrendo uma edição do metadado . Não explicando qual foi a edição do metadado de dado. E não desativação do "veja mais".

**Comment by eduardohumberto** [comment]
Os metadados fixos do repositório foram removidos de alguma forma,ao edita-lo era criado eventos pois não eram considerados metadados pertencentes ao usuário,

Os filtros colocados na tela de adm de metadados do repositório devem ser removidos, e colocados os atuais,  verificar em quais momentos os metadados do repositório estão sendo removidos

**Comment by eduardohumberto** [comment]
Lembrando que um filtro setado no repositório deverá ser alterado apenas em nível de repositório, em coleção não terá efeito

**Comment by juliannyasilva** [comment]
Melhorar o texto no adm dos metadados:
![image](https://user-images.githubusercontent.com/11639242/31129353-aba99464-a82a-11e7-8dd7-e8f12d092435.png)

**Comment by eduardohumberto** [comment]
corrigido

**Comment by juliannyasilva** [comment]
Validado.
