### ISSUE TITLE
[IBRAM] Cadastrar mensagens de ajuda

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#191]

**Comment by leogermani** [comment]
Pelo que me falaram aqui já tem isso. Essa issue é sobre as mensagens de ajuda dos metadados do IBRAM. Eles mandaram um documento com essas mensagens

**Comment by juliannyasilva** [comment]
Anexar aqui o documento com as mensagens!

**Comment by leogermani** [comment]
aqui

[Tainacan_Help_versão 1 (1).docx](https://github.com/medialab-ufg/tainacan/files/1314224/Tainacan_Help_versao.1.1.docx)

**Comment by juliannyasilva** [comment]
Alguns campos estão sem a configuração para inserir textos de ajuda... Logo, necessário estudar como preparar os campos para receber descrição.
