### ISSUE TITLE
Plugin WP - Bloco para Gutenberg

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#195]

**Comment by r-guimaraes** [comment]
As páginas criadas com o Gutenberg são reproduzidas sem problemas, e cabem com o restante do layout editorial do Tainacan

**Comment by r-guimaraes** [comment]
![page-tainacan-gutenberg-editor.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5970f41118eb59001f538600/125516c66e82c728ace21e0d46f8959d26cf97a886e7be40a553bd933c52227d2b01b12c3d80e721ab4d6943434d0eee1e020a17b8eb8339a3bf3b78df590ab8d4380b7cc63a11acbb834ab602bc278c5d99a4fedb1294b7607caddecd5d340c041f83fe5835a69d4ec95cf64ae04953b65e.jpg)

**Comment by leogermani** [comment]
Massa!

O lance é fazer um bloco, inspirado no shortcode que o @andre2ar fez.

Documentação de como criar blocos para o Gutenberg: http://gutenberg-devdoc.surge.sh/
