### ISSUE TITLE
Apresentação de calendário nos metadados de datas na faceta de filtros na home do item, e validação de obrigatoriedade nos formulários de adição e edição

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#199]
Em um filtro do tipo data, ao informar um período e aplicar o filtro não é realizado nenhuma interação no sistema.

**Comment by mbrunodm** [comment]
Tem algum repositório em específico que esse problema ocorre?

**Comment by juliannyasilva** [comment]
Cenário: https://drive.google.com/file/d/0B3Y7QqQ4H6oVb2NZYzRjUVBUWms/view

Assim que identificar o video sobre a não interação do botão posto aqui.... Mas ao retestar este filtro novamente como pode ver no cenário a cima, foi encontra algumas inconsistências:

- [x] Ao editar o metadado data de publicação retirando a data informada, o item mesmo não possuindo mais o valor do metadado, ainda é retorno no filtro de data. 

- [x] A edição na home de edição via configurações do item não são aplicada. Somente é aplicado a alteração se editar o metadado na home do item.

**Comment by juliannyasilva** [comment]
http://dev.medialab.ufg.br/julianny/colecao/imagens-de-copias/

Nesta coleção criei um metadado "Data de submissão" no qual em sua configuração informei que o mesmo é um filtro da coleção, e seu preenchimento é obrigatório. Ao submeter 3 itens via "Adicionar arquivos" e sem informar a data no metadado obrigatório o mesmo permitiu salvar os itens. E ao adicionar mais 2 itens com o valor 01/10/2017 no metadado obrigatório "Data submissão" o mesmo não relacionou os valores ao metadado, e consequentemente não os filtrou. 

Logo as correções iniciais seriam,

- [ ] Ao informar que o metadado é obrigatório, 3 interfaces de submissão (texto, arquivos e url) não deve permitir salvar itens sem informar os valores ao campo.
- [x] Relacionar os valores fornecidos na adição ao metadado do tipo data.
- [ ] Na faceta de filtros, exibir o calendário para seleção de data igual dos formulários de adição.

**Comment by mbrunodm** [comment]
Foi corrigido apenas o que é bug.
A validação de campos obrigatórios não foi implementado para múltiplos arquivos.
