### ISSUE TITLE
Corrigir e definir o redirecionamento das paginas de configuração de uma coleção

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#207]
Na pagina de submissão de item por arquivos, ao acessar a pagina de licenças. Ao clicar no botão "Voltar" na tela de licenças. O sistema emitiu uma mensagem de "Este item foi removido" e redirecionou o usuário para a tainacan coleções. Sendo que o correto era ter sido redirecionado para a coleção onde sua licença estava em edição. E ao acessar de novo a pagina de submissão de item por arquivos, foi apresenta o item que de acordo com a mensagem teria sido removido.

**Comment by mbrunodm** [comment]
Nas telas de adm da coleção, o 'retornar' voltará pra coleção

**Comment by juliannyasilva** [comment]
Cenário: https://drive.google.com/file/d/0B3Y7QqQ4H6oVYkRhZnZsV0M4MFk/view

Apos acessar a pagina adm de config, metadados, etc... E acessar a pagina layout e clicar em "voltar" o sistema emite uma mensagem que o item foi removido.

**Comment by juliannyasilva** [comment]
Retestar mensagens no voltar do layout, metadados;

**Comment by juliannyasilva** [comment]
Cenário: https://drive.google.com/file/d/0B3Y7QqQ4H6oVVlFaMmtsal9ZSkU/view

No tempo 0:23 percebe-se ainda que ao clicar no botão "voltar" o sistema esta emitindo uma mensagem fora do fluxo. 
![image](https://user-images.githubusercontent.com/11639242/31234928-8783bc70-a9c6-11e7-884d-a4a740fe8ce1.png)
