### ISSUE TITLE
Corrigir submissão de item via URL do Vimeo

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#210]
https://drive.google.com/file/d/0B3Y7QqQ4H6oVZjNVRWN4QnZhWXM/view

**Comment by mbrunodm** [comment]
Não importa apenas um vídeo do Vimeo, ou importa os videos de um usuário ou importa os vídeos de um canal.

**Comment by juliannyasilva** [comment]
Verificado e validado.
