### ISSUE TITLE
Travamentos e fluxos não esperados com acessos simultâneos na mesma coleção e/ou coleções diferentes no mesmo domínio

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#219]

**Comment by mbrunodm** [comment]
Julianny, Preciso que este caso seja mais explicado por favor.

**Comment by juliannyasilva** [comment]
Traçar um contexto onde o fluxo não esperado é realizado, até lá, considerar como somente investigação.
