### ISSUE TITLE
Corrigir a definição de licença padrão

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#224]

**Comment by mbrunodm** [comment]
Qual é o problema?

**Comment by juliannyasilva** [comment]
Ao definir uma licença padrão para que a coleção identifique tal coleção é necessário ativa-lá. Ao ativa-la e adicionar um item via "Adicionar texto", no formulario de adição aparece a licença selecionada no metadado 'licença' mas ao salvar o item do tipo texto, e ir na home do item, a licença selecionada na adição não é apresentada no detalhe do item (metadado licença). 

Nos formulários de adição em "Adicionar arquivos" e "Adicionar url" o metadado 'licença' é apresentado de forma diferente da outra interface de adição (adicionar texto), no qual nestes alem de ter que selecionar a licença, possui um botão que não tem na outra interface que ajuda a entender os tipos de licenças. E nestas também ao salvar o item e ir em seu detalhamento não é apresentado no metadado licença a definida na submissão do item.
![image](https://user-images.githubusercontent.com/11639242/32181175-e1f5f160-bd7a-11e7-9fb3-094692fd4115.png)

Logo a correção seria:
- [x] Aplicação da licença padrão definida na adm licenças, em todos os itens submetidos na coleção atraves das 4 interfaces de adição de itens (texto, arquivos, zip e url).
- [x] Relacionamento da licença padrão nos item. Para que assim no detalhamento dos itens o metadado licença apresenta corretamente o valor definido na adição do item.
- [x] Inclusão do botão de ajuda para escolher a licença em todas as interfaces de adição de itens. 
- [x] Padronizar a forma que é apresentado o metadado licença nos formulários de adição, se definido a licença padrão, trazer já seleciona a licença em todos os formulários.
- [x] E ao selecionar uma licença padrão, obrigatoriamente já deveria ativa-la na coleção, ao inves de ter que clicar na coluna ativar para poder aparecer no formulário.
