### ISSUE TITLE
Inserir um botão "Voltar ao topo" na tela de submissão de arquivos

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#229]
https://drive.google.com/file/d/0B3Y7QqQ4H6oVbWRYV2dVSDZHT1k/view

**Comment by juliannyasilva** [comment]
Verificado e validado.

**Comment by juliannyas** [comment]
Ao retestar a funcionalidade é verificado que ao clicar no botão voltar ao topo, esta redirecionando para home da coleção, perdendo a submissão que itens que estava em processo.
