### ISSUE TITLE
Inconsistências gerais no dev-tainacan

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#230]
## Repositório - nivel ADM
- [x] Ao selecionar uma licença padrão do repositório, excluiu o item da coleção. Ver: https://drive.google.com/file/d/0B3Y7QqQ4H6oVT3VJQVBOUXQ5QWc/view
- [x] Redirecionamento inconsistente na configurações da coleção. Veja: https://drive.google.com/file/d/0B3Y7QqQ4H6oVd1hucVhNNnJwbDQ/view
- [x] Pages coleção: https://drive.google.com/file/d/0B3Y7QqQ4H6oVNXpRY1Y0ejhqSlE/view

## Criação da Coleção
- [ ] Na criação de coleção na aba metadados e filtros ao adicionar o metadado de relacionamento e definir os relacionamentos do metadado, e salvar, ao retornar e editar o mesmo os relacionamentos não estão sento apresentados.
![image](https://user-images.githubusercontent.com/11639242/29944755-12dc06e6-8e75-11e7-9736-ca2c04758182.png)
- [ ] Não aplicação do tema escolhido corretamente.
![image](https://user-images.githubusercontent.com/11639242/29944892-7bd0538c-8e75-11e7-8485-44ccd96d6523.png)
- [ ] No layout da coleção renomear a forma de ordenação de Ascendente --- para --- Crescente. Para manter um padrão.

## Visualização da coleção vazia
- [ ] Filtro tipo data com 'até' em minusculo e 'De' em maiúsculo. Renomear até para "Até".
- [ ] Porque os metadados do tipo texto e Relacionamento esta dentro da aba "Categorias" em filtros? Não era para estarem foram igual o metadado/filtro "Data de criação"?
- [ ] Não aplicação no tema escolhido na criação da coleção (Cinza escuro e rosa):
![image](https://user-images.githubusercontent.com/11639242/29945342-2fdd0068-8e77-11e7-8a13-f36260aa21ef.png)
- [ ] Incluir um botão no fim da interface de busca avança, pois quando possui muitos metadados, tem q subir a pagina até o link de busca avançada para ocultar os campos. Melhorar a usabilidade deixando mais explico que é outra forma de pesquisa ou não esconder o campo de busca simples também.

## Edição da coleção
- [ ] Na page de configuração da coleção a edição de capa e miniatura devem ser padronizadas. Alterar de selectbox para botão a exclusão das imagens. E deixar a edição da imagem clicando do campo capa e miniatura, e via botão como na edição de capa.:
![image](https://user-images.githubusercontent.com/11639242/29979517-24f5a02e-8f1c-11e7-94c5-54444435bc0c.png)
- [ ] Ao desabilitar o cabeçalho as opções de compartilhamento da coleção desaparecem;

## Navegação
- [ ] Com a coleção vazia (sem itens) ao acessar a page de exportação, e clicar em 'voltar' sistema emite mensagem que item foi removido. Podendo fazer uma observação que a url esta mostrando "?" que pode ser verificada quando ocorre fluxos alternativos ao esperado. Outra hora apresenta "#".
![image](https://user-images.githubusercontent.com/11639242/29980094-934aba6c-8f1e-11e7-8d62-18eb6b25d5b0.png)

## Criação de item
- [ ] Ao solicitar submissão de item via URL o sistema não carrega a pagina e não altera a url da page para de criação de item.
- [ ] Submissão de item via URL do facebook não esta sendo realizada: https://drive.google.com/file/d/0B3Y7QqQ4H6oVYUU2XzdQaTdGeGM/view
- [ ] Na submissão de item via URL esta podendo ser observado várias inconsistências de acordo com o video: https://drive.google.com/file/d/0B3Y7QqQ4H6oVRVhFZnlzYlpsLTg/view 
- Não identificação colando link via mouse. 
- Diferença no caminho percorrido na criação, do endereço apresentado como url da page.
- Botão de expansão dos metadados não funcionando corretamente.
- Erro na recuperação dos valores dos metadados.
- Erro na apresentação de data invalida no metadado do tipo data.
- Não apresentação das licenças pre cadastradas no repositório.
- Erro na demonstração da seleção de itens quando selecionado todos de uma vez. 
- Apresentação de evento realizado com sucesso com botão de 'ok', mas redirecionamento muito rapido para a home da coleção, não permitindo ler direito o conteudo do pop-up e clicar no botão "ok'. 
- Não relacionamento do item com o metadado de relacionamento das categorias da coleção.

**Comment by eduardohumberto** [comment]
questões de redirecionamento, peço, por gentileza, que seja testado novamente
