### ISSUE TITLE
Fazer listagem de repositórios e coleções

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#236]
A princípio ver se é possível fazer isso apenas com a API do Elastic. 

Plano B fazer isso com as APIs individuais dos tainacans envolvidos, mas o ideal seria não precisar disso.

**Comment by eduardohumberto** [comment]
a listagem de coleções esta situada nos filtros dependendo do resultado da busca.

**Comment by juliannyasilva** [comment]
Validado por @leogermani .
