### ISSUE TITLE
Implementar a notificação de eventos ao moderador na pagina inicial 

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#241]
Cenário: https://drive.google.com/file/d/0B3Y7QqQ4H6oVbmloakdKa0x6b3M/view

Como podemos ver existe na navbar da coleção um sino de notificação onde informa ao moderador os eventos existentes em todas as coleções do repositório.... Logo as correções que devem ser realizadas são:

- [x] implementar a notificação na pagina inicial do repositório.
- [x] remover das notificações eventos de coleções excluídas do repositório. (para evitar paginas não encontradas);
- [x] remover esta pop-up exibido ao acessar a coleção guitarras .
![image](https://user-images.githubusercontent.com/11639242/31145687-de56bb32-a85a-11e7-86da-ceb81b270fd9.png)

**Comment by eduardohumberto** [comment]
Limpar o cache!!

**Comment by juliannyasilva** [comment]
Verificado e validado.
