### ISSUE TITLE
Modulo gestão de documentos:  prazos das categorias 

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#242]
Não estão salvandos os prazos das categorias definidas nas configuracoes avancadas 

![unnamed](https://user-images.githubusercontent.com/971483/31179950-ad7106a0-a8f3-11e7-8773-ea11a293bc77.png)

**Comment by eduardohumberto** [comment]
Reativar o tema Tainacan nesta instalação

**Comment by juliannyasilva** [comment]
Verificado pelo @leogermani .
