### ISSUE TITLE
Modulo de gestão de documentos:  Data de criação

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/tainacan#243]
Nao esta aparecendo a Data de criação do documento (deveria aparecer esse metadado fixo)

![unnamed 1](https://user-images.githubusercontent.com/971483/31179982-c4f16626-a8f3-11e7-8c65-41cc6de7345d.png)

**Comment by eduardohumberto** [comment]
Reativar o tema Tainacan nesta instalação

**Comment by juliannyasilva** [comment]
Verificado pelo @leogermani .
