### ISSUE TITLE
Inconsistências gerais nos eventos em nível anonimo e membro não moderador

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#244]
Cenário 1: https://drive.google.com/file/d/0B3Y7QqQ4H6oVZXFZNkZRYU9wb3M/view

Cenário 2: https://drive.google.com/file/d/0B3Y7QqQ4H6oVUGJxY1ZoZDdSbWM/view

Cenário 3: https://drive.google.com/file/d/0B3Y7QqQ4H6oVODZTdFV5Y1daZ2c/view

## Erros e melhorias:

- [x] Eventos relacionados a item, como a adição de item não esta sendo reportado ao moderador da coleção. O usuário consegue subir o item, mas o moderador não é notificado da submissão... Quando um usuário carrega vários itens de uma vez, o sistema irá criar um evento único tendo na sua descrição o nomes de todos os itens que foram submetidos? Ou é criado um evento de adição de item para cada item? Melhor solução seria um evento único quando se trata de varias submissões. 

- [x] Ao adicionar item texto o sistema redireciona para a pagina inicial. (Tanto anonimo, quanto membro qualquer, sem ser moderador da coleção.)

- [x] Não emissão de mensagem em item enviado para aprovação na submissão de itens. (as config da coleção esta tudo como: aprovação);

- [x] Toda vez que verificar um evento, recarregar a pagina de eventos para deixar somente os eventos que ainda não foram verificados.

- [x] Traduzir as descrições dos eventos para português: 
![image](https://user-images.githubusercontent.com/11639242/31193435-7981b2e6-a91a-11e7-840b-806ea16b68cd.png)

- [x] Ao editar um metadado fixo na home do item, ao emitir a mensagem que "o item foi enviado para aprovação" atualizar a home, fechando a pagina de edição do metadado fixo.  

- [x] Dar espaçamento entre as ações de usuário na descrição do evento:
![image](https://user-images.githubusercontent.com/11639242/31194650-34dc3590-a91e-11e7-857d-0136e7e533f8.png)

- [x]  Na descrição do evento, no link criado para navegar até a coleção e/ou item, quando usuário clicar no link abrir em uma nova aba e não na mesma aba que esta verificando os eventos. Corrigir o redirecionamento do link.

- [x] Criar botão para excluir campos nos metadados multi valores na home do item:
![image](https://user-images.githubusercontent.com/11639242/31194752-818ea99a-a91e-11e7-8d4b-fa322fab7399.png)

- [x] Melhorar a mensagem emitida ao editar um metadado e não salvar para: "Irá perder todas as modificações realizadas, deseja prosseguir?"

- [x] Remover botão estranho da interface de edição de metadado de objeto:
![image](https://user-images.githubusercontent.com/11639242/31195661-69fe3e96-a921-11e7-869d-ae47e08bfcc8.png)

- [ ] Implementar uma forma de sugerir itens mas facilmente, porque se o usuário não tem noção do relacionamento, fica sem saber o que buscar.

- [x] Não permitir criar um metadado de objeto (relacionamento) se não possuir nenhum relacionamento com alguma categoria.

- [x] Melhorar a interface de criação de categorias na home do item: 
![image](https://user-images.githubusercontent.com/11639242/31196910-c07f607a-a925-11e7-8884-298169d45420.png)

- [x] Evento de criação de metadado de termo por mas que confirma o evento, e salva. O sistema não faz nenhuma interação, não movendo para verificado, e não permitindo a criação do metadado de termo. 

- [x] Traduzir para portugues os textos de ajuda na criação de metadado de dado:
![image](https://user-images.githubusercontent.com/11639242/31197456-8ef0c858-a927-11e7-915b-2f5cb9cb48c8.png)

- [x] Retirar a mensagem de item removido na home da coleção, pois foi realizado a remoção de uma tag e não um item:
![image](https://user-images.githubusercontent.com/11639242/31197626-1227aa66-a928-11e7-8258-a88dc68be6cc.png)

- [x] Na criação de uma tag na home do item é criado dois eventos, um de "criar tag na coleção" e outro "criar classificação no item", mas na remoção de uma tag só é criado um evento "deletar classificação". Porque? Deveria criar dois eventos também como deletar tag e deletar classificação, seguindo mesmo raciocínio de adição.
![image](https://user-images.githubusercontent.com/11639242/31197743-6cd2b7e4-a928-11e7-85b4-3abb268c5bfe.png)

**Comment by eduardohumberto** [comment]
"Na criação de uma tag na home do item é criado dois eventos, um de "criar tag na coleção" e outro "criar classificação no item", mas na remoção de uma tag só é criado um evento "deletar classificação". Porque? Deveria criar dois eventos também como deletar tag e deletar classificação, seguindo mesmo raciocínio de adição."


Só um porque remove apenas a classificação e não deleta a tag, então comportamento esta correto

**Comment by eduardohumberto** [comment]
" Quando um usuário carrega vários itens de uma vez, o sistema irá criar um evento único tendo na sua descrição o nomes de todos os itens que foram submetidos? Ou é criado um evento de adição de item para cada item? Melhor solução seria um evento único quando se trata de varias submissões."

é criado um evento para cada item,   pois são valores específicos em seus metadados, e no momento da confirmação do evento é possível ver um preview de cada item a ser confirmado.

Uma melhoria futura seria aprovar ou não vários eventos ao mesmo tempo, mas por enquanto temos essa limitação.

**Comment by eduardohumberto** [comment]
" Implementar uma forma de sugerir itens mas facilmente, porque se o usuário não tem noção do relacionamento, fica sem saber o que buscar."

Este é um campo a ser discutido pois no início este campo era um selectbox, mas aí entra coleções com milhares de itens,  com autocomplete isso resolveu porém perde-se no conhecimento dos itens do relacionamento, é uma questão ampla pois todos os locais que utilizam este metadado de relacionamento seriam afetados.

**Comment by juliannyasilva** [comment]
- [ ]  Não permitir criar um metadado de objeto (relacionamento) se não possuir nenhum relacionamento com alguma categoria.... Traduzir a mensagem:
![image](https://user-images.githubusercontent.com/11639242/31293341-456bb4ea-aaad-11e7-8ada-9e6366e9fb72.png)

**Comment by juliannyasilva** [comment]
Verificado.
