### ISSUE TITLE
No metadado de categoria apos habilitar adicionar nova categoria, o botão para adicionar nova categoria não aparece no "Adicionar Item"

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#248]

**Comment by juliannyasilva** [comment]
De acordo com email recebi do Marcel, 

"> No modal Adicionar metadado de categoria (tela metadados) tem a opcao abaixo:
![image](https://user-images.githubusercontent.com/11639242/32004613-f609efce-b980-11e7-8c4d-7117db555315.png)
Entretanto, ao habilitar essa opcao (SIM) nao mostra o botão abaixo nem a possibilidade de criar subcategoria com o botao direito do mouse na tela de adicionar/editar item (isso estava funcionando no adicionar item antigo).

PS: Isso funcionava antes."

Retorno a issue para correção e inclusão do botão de adicionar nova categoria na adição e edição de item em todos os formulários respectivamente.

A função de adicionar uma subcategoria clicando com o botão direito também deve estar funcionando no dynatree do formulário do adicionar item ao habilitar a nova categoria no modal.

**Comment by juliannyasilva** [comment]
Nas interfaces de envio via arquivos e url não aparece o botão para adição de uma nova categoria. 
![image](https://user-images.githubusercontent.com/11639242/32187346-ecfae30c-bd8b-11e7-98f8-893c3dfe1abb.png)

Somente na interface de envio via texto.
![image](https://user-images.githubusercontent.com/11639242/32187407-1cb556fe-bd8c-11e7-8073-07b59d63f315.png)

**Comment by marcelf** [comment]
O Nova Categoria nao ficou correto, pois nao tem como eu criar uma subcategoria (Na imagem abaixo eu quero criar a profissao Cirurgião debaixo de Médico)

Para solucionar, no campo Categoria pai do modal, mostrar a hierarquia de categorias a partir da categoria raiz selecionada no metadado de categoria (no exemplo é Profissão).
http://dev.medialab.ufg.br/fuppy/colecao/pessoas/add/
Dessa forma o usuário podera mudar a categoria pai para qualquer categoria abaixo da categoria raiz selecionada na criacao do metadado de categoria, sendo que essa categoria é a default (ja esta assim hoje, no exemplo é Profissão, o usuário poderia criar debaixo de Profissão ou de uma subcategoria de profissão no caso Médico).

![image](https://user-images.githubusercontent.com/543662/32502180-34d87de8-c3c1-11e7-9d1f-d321164e7baf.png)

**Comment by juliannyasilva** [comment]
O botão de adicionar nova categoria esta sendo apresentado mesmo quando o metadado não esta habilitado a opção.

**Comment by juliannyasilva** [comment]
Validado.
