### ISSUE TITLE
Metadado de texto longo não permite inserir múltiplos valores

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#251]
Um metadado de texto longo ao ser definido como múltiplos valores e colocado dentro de um metadado composto não permite múltiplos valores (não tem o botão para adicionar mais um).

**Comment by eduardohumberto** [comment]
Metadados de texto dentro de compostos por mais que sejam multi-valorados, não é permitido adicionar mais valores, isso não foi implementado, a única possibilidade é colocar  o composto como multi-valorado. Para poder adicionar mais valores exclusivamente para o metadado ele deve estar fora do composto

**Comment by juliannyasilva** [comment]
Verificado, e ok.
