### ISSUE TITLE
Não submissão de grandes quantidades de imagens via 'Adição por arquivos'

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#261]
O Johan subiu um conjunto de arquivos numa coleção de 621 imagens, na instalação http://johanpdr.medialab.ufg.br/colecao/fotografias-de-thomas-hoag/. Mas os arquivos não são apresentados na coleção. Quando entra em Adicionar > Enviar Arquivos vai para “continue editando” e elas estão todas lá. Mesmo enviando elas nessa etapa, ainda assim a coleção continua vazia.

**Comment by marcelf** [comment]
Isso ocorreu comigo tambem, tem que ver no php.ini se essa configuracao esta ok:

max_file_uploads	20	20

Como vc pode ver o default é bem baixo. Eu coloquei (2000). Outra coisa, sao os limites de envio de arquivo e memory (aumenta para 256M):

memory_limit	64M	64M

**Comment by eduardohumberto** [comment]
Enviei algumas alterações na branch dev ( 225d73c ), deve ajudar no desempenho, consegui enviar 660 imagens nesta instalação http://dev.medialab.ufg.br/tainacan/cole%C3%A7%C3%A3o/user-eduardo/, cada qual com quase 1 mega, se caso nas outras instalações persistir sugiro verifcar o que o @marcelf  falou, o walison deve ajudar nessa questão, também testei alguns PDFs e parece que está ok, se possível em caso de erro, anexar os casos de teste.

**Comment by juliannyasilva** [comment]
Verificado e validado.

**Comment by juliannyasilva** [comment]
Erick reportou que o travamento desta issue esta ocorrendo em seu site http://ungarelli.medialab.ufg.br/colecao/livros/ no qual em alguns testes na maquina dele verificamos dois casos. 

1- O problema não ocorre por exemplo no dev.medialab que esta na branch dev. Ou seja, por a branch dele estar na master provavelmente seja corrigir este travamento na master.

2- O Erick reportou que o travamento ocorre a partir de um n° grande de arquivos. E durante o travamento se der F5 ou voltar a pagina os itens aparecem na coleção. 

Logo, poderia resolver este caso, caso a reindexação de miniaturas de pdf estivesse funcionando, mas também na reindexação esta ocorrendo o mesmo travamento. A diferença é que no envio de itens só deu um erro no console do navegado error 500. Agora no travamento da reindexação foi apontado no console vários erros, caso seja necessário, podemos tirar print dos erros.

Logo, aplicar as correções na branch master, para que sites hospedados com esta branch funcione corretamente.

**Comment by eduardohumberto** [comment]
Solicitar a aplicação desta branch nesta instalação

**Comment by leogermani** [comment]
Se isso foi corrigido na dev e é um erro que está atingindo muita gente vamos fazer um novo release!

**Comment by juliannyasilva** [comment]
Antes de fazermos o release, vou testa em instalações locais em abas branchs, e procurar um servidor que esteja na dev alem do dev.medialab pra realmente analisar as aplicações de correções. E então lança o release.

**Comment by leogermani** [comment]
ok

**Comment by juliannyasilva** [comment]
Foram realizados testes em instalações locais em abas branchs, e em instalações em produção com o tainacan. E todos os casos foram submetidos corretamente grandes números de arquivos. Logo os casos de travamentos devem ser tratados isolados.
