### ISSUE TITLE
Não submissão de item via URL

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#263]
- [x] Caso de teste: Em dev.medialab.ufg.br/tainacan, ou /julianny, acessar uma coleção e clicar em "Inserir URL", informar no campo o valor "www.google.com", o sistema identifica como www e prossegue. Apos editar o item que é identificado como texto, e informar os valores aos metadados como desejado, clicar em "salvar". O item que foi inserido não é apresentado na coleção, ou seja, não é criado. O caso foi testado com outras urls, incluindo url de um video do youtube por exemplo.

- [x] Ao Adicionar uma URL o item esta sendo cadastrado como TEXTO. Para corrigir alterei para outro, mas ai o link para o site ficou errado.

- [x] Ao enviar uma URL do Facebook não identifica como WWW, e não deixa ir para a próxima etapa (fica travado). O facebook foi retirado da lista de redes sociais por causa da api, mas ficou alguma coisa no código que esta barrando o envio de links do facebook como se fosse WWW.

- [x] Esta dando essa mensagem abaixo para algumas URL. Quando nao conseguir nenhuma informacao, passar para a próxima etapa com os campos de titulo e descrição vazios (apenas com o de conteudo preenchido com a URL), para não mostrar essa mensagem. ![image](https://user-images.githubusercontent.com/11639242/32225556-b91aa2e2-be2c-11e7-89eb-9761af336625.png)

**Comment by juliannyasilva** [comment]
- Ao tentar enviar um link do facebook, não permitiu. Logo, esta acordado que nenhuma url referente ao facebook poderá ser adicionado no repositório? 

- Ao tentar enviar a mesma URL esta tendo dois fluxos que redireciona para interfaces de adição diferentes. 
https://drive.google.com/file/d/0B3Y7QqQ4H6oVM0pvQlBFT1V3Zzg/view?usp=sharing
Ocorre o fato quando seleciona ou não "Extrair metadados". Há necessidade realmente de manter duas interfaces de adição neste caso, se sim, é necessário adiantar as melhorias da issue #215 para deixar a adição mais completa. E teria que aplica as correções da issue #265 neste contexto. 

Como é uma submissão de URLs (normalmente vai querer abrir links) não tem pq relacionar tais como tipo 'texto', o mais certo seria deixar como tipo 'outro' mesmo. Tomando esta logica, não a necessidade de abrir a tela de adição (escrever texto) nesse fluxo, e deixar a tela de adição padrão ao de enviar arquivos. Logo, definir qual seria a melhor interface neste caso.

**Comment by eduardohumberto** [comment]
A função "Extrair metadados" será desabilitada por estar defasada com as versões atuais do tainacan,  os demais pontos citados no primeiro comentário serão corrigidos

**Comment by juliannyasilva** [comment]
Esta issue tem relação com outra criada anteriormente, logo as modificações a respeito da padronização de interfaces de adição, serão aplicadas na issue #216 . No qual ao encerrar esta, ambas estarão concluídas.

**Comment by juliannyasilva** [comment]
Tendo em conta que a função de "Extrair metadados" será desabilitada. Pode ser considerado então o encerrado das issues  #218 e #215 .

**Comment by mbrunodm** [comment]
Ao tentar enviar um link do facebook, não permitiu. Logo, esta acordado que nenhuma url referente ao facebook poderá ser adicionado no repositório?
Facebook e Instagram foram removidos. Não serão importados.

**Comment by juliannyasilva** [comment]
Os itens adicionados com a url contendo "www." não é possivel abrir o link do arquivo na home do item.

**Comment by juliannyasilva** [comment]
O que se percebe que só identifica e cria o item corretamente se colar a url... Um exempo pode ser visto nos seguintes itens:

- Item criado digintando a url: https://dev.medialab.ufg.br/julianny/item/techtudo-a-tecnologia-descomplicada-2/

- Item criado colando a mesma url: https://dev.medialab.ufg.br/julianny/item/techtudo-a-tecnologia-descomplicada/

Na url colada percebe que o metadado fonte esta diferente e o link do arquivo correto.
