### ISSUE TITLE
Não relacionamento dos metadados de uma coleção ao item

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#264]
### Adicionando o item via "Escrever texto"
![image](https://user-images.githubusercontent.com/11639242/32189827-03ac86a8-bd93-11e7-8127-20f0733dac70.png)
![image](https://user-images.githubusercontent.com/11639242/32189848-100809b8-bd93-11e7-9433-276a7d554a30.png)

### Apos salvar o item via 'Escrever texto"
![image](https://user-images.githubusercontent.com/11639242/32189925-4b046908-bd93-11e7-8d07-61a4dbc245e8.png)
![image](https://user-images.githubusercontent.com/11639242/32189982-76d6bd92-bd93-11e7-9a0f-57994dcd539a.png)

### Adicionando o item via "Adicionar arquivos"
![image](https://user-images.githubusercontent.com/11639242/32190150-06a129f8-bd94-11e7-9a9d-04108db49b37.png)
![image](https://user-images.githubusercontent.com/11639242/32190184-1a17d7fc-bd94-11e7-87c7-498739b8ebc9.png)

### Apos salvar o item via "Adicionar arquivos"
![image](https://user-images.githubusercontent.com/11639242/32190387-cf06bb1a-bd94-11e7-8879-ee83132bb805.png)
![image](https://user-images.githubusercontent.com/11639242/32190403-db16f7d0-bd94-11e7-8f51-729b8bf3b29b.png)

Na interface via arquivo comprimido não possui interface para manipulação de metadados. E a interface de envio via url esta em correção #263.

### Logo como podemos ver nas interface e durante o fluxo dos testes:

- [x] Ao criar uma coleção na aba metadados, ja vem como padrão o nome "Assunto da <nome da coleção>, mas se alterarmos este nome ele não é substituído ao salvar. O metadado continua sendo "Assunto da <nome da coleção>", mas é criado um filtro na aba de filtros com o nome fornecido. Aparentemente 'assunto da ...' é um padrão, logo pq deixar este campo editável? 

- [ ] Apresentação do metadado ASSUNTO em branco, e não apresentação de sua subcategoria. 
![image](https://user-images.githubusercontent.com/11639242/32190871-55f91496-bd96-11e7-8ce7-63d4ad8fa912.png)

- [ ] O não relacionamento de valores nos metadados FONTE, ASSUNTO, LICENÇA.

**Comment by eduardohumberto** [comment]
No momento em que é criado um metadado de categoria e colocado como filtro, o nome que vai para os filtros é o do próprio metadado, porém após essa primeira listagem o nome que fica é o de sua categoria raiz, o que no caso seria Assunto da <nome da coleção>. Este comportamento se dá pq no momento da criação não há como saber qual categoria foi selecionada como raiz do metadado, após outro carregamento essa informação já vem do servidor. Lembrando que na tela de metadados é possível alterar apenas o metadado e não a categoria raiz!

**Comment by juliannyasilva** [comment]
https://drive.google.com/file/d/1NRjCEqwUGDAhqJgVKI4I6Gk3A7Ax2AJ9/view?usp=sharing

- [ ] Não relacionamento de valores nos metadados do tipo FONTE, CATEGORIAS, LICENÇA. E quando é relacionado não apresenta na home do item o valor, e sim, o botão de campo vazio. Mas ao clicar no botão é possível visualizar o relacionamento com o metadado.

**Comment by eduardohumberto** [comment]
http://ibram.medialab.ufg.br/wp-json/tainacan/v1/collections

2017-11-09 11:39 GMT-02:00 Julianny Alves <notifications@github.com>:

**Comment by juliannyasilva** [comment]
Validado.

**Comment by juliannyasilva** [comment]
Instalação: http://www.pesquisajuventude.ufscar.br
Item que não relacionou os valores dos metadados: http://www.pesquisajuventude.ufscar.br/item/2-introduction-to-metadata_-setting-the-stage/

Nas instalações com o Tainacan esta sendo criado metadados em coleções e ao adicionar arquivos informando valores neste metadados e salvar o item. Ao visualizar o item não esta sendo apresentado nos metadados os valores informados. Este caso esta acontecendo em varias instalações como o medialab, gi.fic, pesquisajuventude, etc.

**Comment by juliannyasilva** [comment]
Em testes rodando no wordpress local

Erro apontado no console ao salvar 2 itens enviados: 
![image](https://user-images.githubusercontent.com/11639242/32896924-73f2ec6e-cacb-11e7-86e0-a118531a42a4.png)

Ao clicar em salvar, fica eternamente na tela: 
![image](https://user-images.githubusercontent.com/11639242/32897207-1bea8be8-cacc-11e7-80bc-50672b94e3c5.png)
E no console aponta o seguinte erro:
![image](https://user-images.githubusercontent.com/11639242/32897278-42aacebe-cacc-11e7-988e-e18680aab464.png)
