### ISSUE TITLE
Ao editar um item do tipo 'Texto' e passar o tipo para 'Outro' (URL) não ocorreu a mudança de interface. Não foi possível inserir a url e continuou a aparecer a caixa de texto.

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#265]

**Comment by eduardohumberto** [comment]
realizei uma alteração para colocar a url direto no campo de texto mesmo, dessa forma basta colocar a url no mesmo campo de texto

**Comment by juliannyasilva** [comment]
Para deixar mais claro a mudança na tela para o usuário, realizar a melhoria de imprimir no titulo do campo ou dentro do campo de texto uma descrição, do tipo, insira aqui o conteúdo ou a url do item. Para informar ao usuário que o mesmo deve colar a url dentro do campo de texto.
![image](https://user-images.githubusercontent.com/11639242/32447609-bf11bbc4-c2f3-11e7-877b-b1f2db99f1af.png)

**Comment by eduardohumberto** [comment]
inserido uma mensagem no título

**Comment by juliannyasilva** [comment]
Verificado e validado.
