### ISSUE TITLE
Importar do Youtube não só a URL do navegador mas também a URL do vídeo

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#267]
Ao tentar inserir uma URL copiada do vide (e não na barra de navegação) o sistema emite a seguinte mensagem: 
![image](https://user-images.githubusercontent.com/11639242/32240454-8a39f216-be54-11e7-9312-287d2e74b004.png)

Neste casa de URL não é possivel importar gerando a miniatura e salvando como tipo video... Deveria pelo menos importar como WWW com o tipo outro. Pois pelo menos teria o campo para abrir o video.

Em outras instalações é possivel importar, mas importa como texto e não video.

**Comment by andre2ar** [comment]
Necessário criar nova instalação para realizar teste, também é necessário inserir a chave de API do YouTube para realizar os testes.

**Comment by juliannyasilva** [comment]
Validado parcialmente.
