### ISSUE TITLE
Melhorar o tratamento da tipologia na adição e edição de itens

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#268]
Cenário: https://drive.google.com/file/d/0B3Y7QqQ4H6oVUWhGZlJfblBYT1E/view

O alterar o tipo do Item não esta funcionando bem portanto rever essa funcionalidade, o que deve ocorrer na interface do adicionar/editar item quando altera o tipo do item?

Exemplo de um erro é #265 que acontece por não esta funcionando bem as tipologias dos itens.

**Comment by eduardohumberto** [comment]
fica facultado ao usuário essa tipologia, o tainacan  vai tentar renderizar de acordo do lhe foi selecionado, no caso #265 unifiquei o campo de texto para receber url e conseguir renderizar o vídeo, audio, ou imagem. Lembrando que arquivos não são suportados nessa tela apenas como anexo
