### ISSUE TITLE
Exportação e importação de pacotes de coleções Tainacan não esta funcionando

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#270]

**Comment by eduardohumberto** [comment]
testei nesta instalação (https://dev.medialab.ufg.br/tainacan ) e está ok, mas localmente tive que habilitar  a extensão zip, caso seja em outra instalação talvez seja o mesmo problema

**Comment by juliannyasilva** [comment]
A exportação esta ocorrendo corretamente e importação também, mas possui algumas melhorias como exportar a capa e miniatura da coleção , e ao importar validar os nomes das coleção para não ter duplicações.
