### ISSUE TITLE
Ao mudar o nome da coleção não é alterado o nome da categoria da coleção e a url 

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#276]
![image](https://user-images.githubusercontent.com/11639242/32553361-dae37208-c47d-11e7-91fd-625c97411e9e.png)

**Comment by mbrunodm** [comment]
Não é feito automaticamente e sim manualmente, o nome da categoria é alterado apenas na tela de gerenciamento de categoria, e o slug da coleção altera nas configurações
