### ISSUE TITLE
Limpar buscar de um metadado de relacionamento na submissão de item limpa todos os campos do formulário

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#291]
Limpar buscar de um metadado de relacionamento na submissão de item limpa todos os campos do formulário, no qual deveria limpar somente o campo de busca do metadado em si.

Que ocasiona erros nos outros campos como exemplo:
![image](https://user-images.githubusercontent.com/11639242/32895311-c0eb6104-cac6-11e7-9026-6bed0e792a1d.png)

**Comment by juliannyasilva** [comment]
![image](https://user-images.githubusercontent.com/11639242/33146433-42a67164-cfab-11e7-8a75-e9615acad857.png)

Ainda limpando todos os campos.

**Comment by juliannyas** [comment]
Ao criar um metadado de relacionamento nivel repositorio, o mesmo não esta setando as categorias, bem como não permitindo sua ocultação nas configurações da coleção, e não esta sendo apesentado na inserção de itens....
E fora do padrão de interface dos outros metadados.
![image](https://user-images.githubusercontent.com/11639242/36496674-c0c1ec32-1717-11e8-8fef-19714e5b96b0.png)
