### ISSUE TITLE
Não apresentação de resultados de uma categoria em um metadado de relacionamento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#292]
Em uma coleção que possui um metadado de relacionamento chamado 'cores' no qual possui o termo selecionado 'Cor' que é uma categoria de usuário de cores padrões. Ao submeter um item e no formulário de preenchimento de dados do item, se pesquisar no metadado 'cores' uma cor ou trazer todos é apresentado a mensagem de não resultados para serem apresentados.

**Comment by eduardohumberto** [comment]
a categoria que deve ser selecionada em um relacionamento, são categorias de coleção, porque os itens precisam estar vinculados a categoria selecionada
