### ISSUE TITLE
'Duplicar em outra coleção' dentro da home do item não funciona

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#295]

**Comment by eduardohumberto** [comment]
retirei da pagina de itens,  da forma como esta hj teria que duplicar o código para poder executar na página de itens, nesse momento é melhor não piorar as coisas

**Comment by juliannyasilva** [comment]
O Andre hj tem uma demanda que precisa duplicar itens, poderia ate retirar a funcionaldiade da home do item, mas na home da coleção não redirecionar a pagina para a coleção de destino. Pode retirar @eduardohumberto o redirecionamento da home da coleção para a coleção de destino ao duplicar um item?

**Comment by juliannyasilva** [comment]
Corrigir o botão 'ok' oande ao clicar no mesmo não abrir aba para edição do item, somente ignorar a mensagem e continua o fluxo.
