### ISSUE TITLE
Não permite ter mais de duas votações do tipo estrela

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#299]
Possuo 3 metadados de votações sendo 1 de estrala e duas de curtir. Ao tentar alterar uma de curtir para estrela não permite.

**Comment by mbrunodm** [comment]
Onde está acontecendo? Em que página?

**Comment by juliannyasilva** [comment]
http://bibflora.medialab.ufg.br/item/pachira-aquatica_2332888215_o/

Um exemplo pode ser visto nesta coleção onde possui 3 metadados de votações, onde ao tentar alterar um desses para estrelas não permite.
