### ISSUE TITLE
Metadados compostos com alterações na home do item inconsistente 

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#300]
![image](https://user-images.githubusercontent.com/11639242/33375412-f80be832-d4f0-11e7-8060-3a619662abb8.png)

- Em um metadado composto onde os metadados que o compoe não são obrigatorios não permite deixar campos em brancos.

- Não persiste valores no metadado numerico.

- Não apaga valores ao editar e salva os novos, pelo contrario, mantem e os duplica.

**Comment by andre2ar** [comment]
Problema não encontrado

**Comment by juliannyasilva** [comment]
Em um metadado composto onde os metadados que o compõe não são obrigatórios não permite deixar campos em brancos.

Ao limpar um metadado composto apaga todos os metadados contidos no metadado composto, deveria somente limpar os campos.
