### ISSUE TITLE
Corrigir inserção de anexos

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#341]
Alguns itens, ao inserir um anexo e salvar, a imagem principal antiga passa a aparecer como o único anexo, e o anexo recém inserido desaparece. Porém, após uma segunda tentativa de inserção, ficam os dois arquivos como anexos, a imagem antiga (nao selecionada para entrar nos anexos) e a recém inserida nos anexos. Ex.: 250 e 312

https://mhn.medialab.ufg.br/item/caixa-de-cha/

**Comment by andre2ar** [comment]
Problema não encontrado
