### ISSUE TITLE
Corrigir redimensionamento de anexos na home do item

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#345]

**Comment by juliannyas** [comment]
Aumentar o scroll do mCorrigir redimensionamento de odal pois o scroll só vai ate a metade do item em janelas pequenas.

**Comment by juliannyasilva** [comment]
A exibição de anexos com resolução muito grande esta estourando a tela, fazendo com que não seja possivel nem avançar e fechar o modal de anexos, alem de não apresentar a imagem completa.
