### ISSUE TITLE
Permitir edição do rodape

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#354]

**Comment by andre2ar** [comment]
O rodapé já pode ser editado, basta ir no wp-admin > widgets. Lá podem ser vistas as opções de edição de rodapé.

**Comment by juliannyasilva** [comment]
Permitir alterar as informações, bem como excluir o rodape ou substituir por uma imagem

**Comment by andrebenedito** [comment]
Exclui o rodapé, recarreguei a página e ele desapareceu. Ao recarregar novamente o insolente voltou a aparecer. https://dev.medialab.ufg.br/itaipu/wp-admin/widgets.php
