### ISSUE TITLE
Edição de um metadado

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#4]
Estou fazendo testes com no site : http://medialab.ufg.br/democraciadigital
Estou editando os metadados da coleção Ferramentas: http://medialab.ufg.br/democraciadigital/ferramentas/admin/metadados

Criei um metadado de categoria com o nome "Ano de Término", só que esqueci de colocar duas variáveis, sendo que ao tentar editar as variáveis para incluir outra, o sistema não permite, eu clico na opção "Clique aqui para editar o nome da categoria" e não funciona

**Comment by juliannyasilva** [comment]
Verificado.
