### ISSUE TITLE
Taxonomias estados e cidades

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#48]
Inserir as taxonomias de  estados e cidades.

**Comment by juliannyasilva** [comment]
Verificar a taxonomia de estados e cidades, itens faltantes !

No campo "Estado/Provincia/Cidade " no IBRAM por exemplo, não esta presente todos os estados do Brasil, faltando os estados (Mato Grosso, Roraima, Sergipe e Tocantins). 

Lista correta segue abaixo:
Acre (AC)
Alagoas (AL)
Amapá (AP)
Amazonas (AM)
Bahia (BA)
Ceará (CE)
Distrito Federal (DF)
Espírito Santo (ES)
Goiás (GO)
Maranhão (MA)
Mato Grosso (MT)
Mato Grosso do Sul (MS)
Minas Gerais (MG)
Pará (PA)
Paraíba (PB)
Paraná (PR)
Pernambuco (PE)
Piauí (PI)
Rio de Janeiro (RJ)
Rio Grande do Norte (RN)
Rio Grande do Sul (RS)
Rondônia (RO)
Roraima (RR)
Santa Catarina (SC)
São Paulo (SP)
Sergipe (SE)
Tocantins (TO)

**Comment by juliannyasilva** [comment]
Verificado, e implementado corretamente.
