### ISSUE TITLE
Atualização do Tainacan Museu via API

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#49]
Desenvolver processo para atualização das colecoes, categorias e propriedades com os seus respectivos metas, atraves da API. No final do processo deve tambem atualizar os arquivos do tema e do plugins do ibram. A ideia é criar um outro plugin separado que executa essa operacao. Na instalacao do tainacan a ser atualizada, o admin deve inserir o link da instancia central que sera usada como modelo na area de admin do wordpress.

**Comment by juliannyasilva** [comment]
Verificado.
