### ISSUE TITLE
Quando uma categoria tem muitas opções, gera um problema de usabilidade

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#5]
Criamos uma categoria para mapear o ano de início de uma determinada ferramenta. acontece que colocamos uma sequencia de 10 anos e o sistema gera uma quebra de texto para um "ver mais" que acaba confundindo o usuário. 

Da pra ver aqui: http://medialab.ufg.br/democraciadigital/ferramentas/

**Comment by leogermani** [comment]
@andre2ar o que foi feito aqui?

**Comment by andre2ar** [comment]
Não encontrei nenhum problema, deve ter sido corrigido anteriormente.

**Comment by leogermani** [comment]
Essa é uma questão que vários usuários estão reportando, de confusão ali com aquele "Ver mais". Vamos fazer uma issue específica para atacar essa questão. Fecho essa por agora.
