### ISSUE TITLE
Descarte   - Regras de Negócio

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#50]
Ao solicitar a finalização do registro de Descarte, o sistema deverá verificar:

(a)    Se os campos obrigatórios foram fornecidos;
Após as verificações, o sistema deverá:

 

(a)    Criar um registro de Descarte;

 

(b)   Se no campo “Modo” for selecionada a opção “Alienação”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Alienado”.

 

Se no campo “Modo” for selecionada a opção “Cessão”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Cedido”.

 

Se no campo “Modo” for selecionada a opção “Inutilização”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Inutilizado”.

 

Se no campo “Modo” for selecionada a opção “Transferência”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Transferido”.

**Comment by juliannyasilva** [comment]
Verificado sem inconsistências.
