### ISSUE TITLE
Texto a partir de PDF

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#51]
Ao adicionar um PDF (fazer upload) o sistema deve gerar seu conteudo texto e associar ao item (usar o postmeta da busca central).

Dessa forma, deve ser possivel ao usuario buscar por um item atraves de uma palavra dentro do pdf. Isso deve ocorrer quando os pdf sao importados na api oai-phm, adicionar zip, pacote tainacan, etc).

NOTA: se possível encontrar uma biblioteca que ja faz isso para pdf e documentos do office

Plugins/bibliotecas:

convert pdf/msoffice em texto
http://silvercoders.com/en/products/doctotext/  +++++ converte tudo (office e pdf) para txt
antiword http://www.winfield.demon.nl/  +++ > muito usado 
http://docx2txt.sourceforge.net/
http://www.wagner.pp.ru/~vitus/software/catdoc/
http://abisource.org/
http://dag.wiee.rs/home-made/unoconv/

The Apache Tika™ toolkit detects and extracts metadata and text content from various documents - from PPT to CSV to PDF
http://tika.apache.org/download.html

http://meta-extractor.sourceforge.net/
The Metadata Extract Tool includes a number of 'adapters' that extract metadata from specific file types. Extractors are currently provided for:
Images: BMP, GIF, JPEG and TIFF.
Office documents: MS Word (version 2, 6), Word Perfect, Open Office (version 1), MS Works, MS Excel, MS PowerPoint, and PDF.
Audio and Video: WAV, MP3 (normal and with ID3Tags), BFW, FLAC.
Markup languages: HTML and XML.
Internet files: ARC
The Tool is written in Java and XML and is distributed under the Apache Public License (version 2).

**Comment by juliannyasilva** [comment]
Verificado.
