### ISSUE TITLE
[Tainacan] Correções na ordenação

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#54]
Testado em: http://medialab.ufg.br/rhs/publicacoes/

1. Retirar os metadados fixos da ordenação:
- Tipo
- Formato
- Licenças
- Anexos
- Miniaturas
- Descrição
- Conteudo

2. Deixar a opção de ordenação atual (decrescente ou crescente) visivelmente habilitada (hj nao da para saber qual esta habilitada)

3. A ordenação crescente e decrescente nao esta funcionando

4. Ao escolher algum metadado (ex Titulo) para ordenar nao mostra nenhum item. O mesmo ocorre para votações.

**Comment by juliannyasilva** [comment]
Os metadados fixos foram retirados e a ordenação atual dos metadados fixos esta visível e funcionando. 

Cenário: http://dev.medialab.ufg.br/tainacan/permanente/
Mas ao selecionar um **metadado de dado** (ex. Titulo, Denominação), o sistema filtra os itens que possui este metadado preenchido, mas a ordenação não acontece corretamente para tal ordenação. 

**Inconsistência 1:** Na ordenação por metadado de dado, não apresenta todos os metadados da coleção.

**Inconsistência 2:** Ao selecionar um metadado de dado para ordenação, o sistema em alguns metadados trás itens com campos vazios, outros não trás itens com o campo vazio. E não trás todos os itens da coleção. 

**Inconsistência 3:** A sentido da ordenação (crescente ou decrescente) não funciona corretamente para ordenação por metadados de dados.
