### ISSUE TITLE
Campos Bloqueados - Inserção do Item - Protótipo IBRAM

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#59]
No cadastro de bem permanente o campo "Situação" é bloqueado para edição. No entanto ao utilizar o mecanismo de rascunho, que permite manter um rascunho com os dados já inseridos no formulário mesmo após uma atualização, ao preencher este campo uma vez e atualizar a página o campo retorna bloqueado para edição, considerando que o item ainda nem foi salvo. Teoricamente o campo deveria permite a sua edição.

**Comment by juliannyas** [comment]
O campo "situação" possui valores na adição de um bem, e podem ser alterados caso seja criado um descarte e desaparecimento relacionando este bem. Mas como na adição de um bem permanente pode setar também o valor "Baixa excluído". Teoricamente o @walisonjose esta correto em seu pensamento, e neste caso o campo "situação" era pra ser editável.

Será feito esta alteração, ou será considerado o campo como esta atualmente (não editável) ? @walisonjose e @eduardohumberto ?

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
