### ISSUE TITLE
Bug ao preencher o cadastro de um metadado "composto"

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#6]
Quando se tem um metadado composto com opções de categoria, ao selecionar o primeiro item no formulário de preenchiemnto, a sanfona fecha automaticamente, sendo que para continuar preenchendo é preciso clicar novamente na aba do metadado. 
Ver em : http://medialab.ufg.br/democraciadigital/ferramentas/

**Comment by leogermani** [comment]
@andre2ar consegue referenciar aqui os commits que vc fez relacionados a essa issue?

**Comment by juliannyasilva** [comment]
Verificado, e acesso ao site em questão não esta disponível .E pela descrição dada não deixa claro o bastante para tentar reproduzir no tainacan dev.medialab o fluxo. Mas o cadastra de metadados composto no tainacan esta com fluxo normal, logo considerado como corrigido.
