### ISSUE TITLE
Metadado relacionamento - Listagem Pesquisa- Protótipo IBRAM

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#60]
Ao realizar uma pesquisa em metadado de relacionamento com cardinalidade múltipla onde são trazidos todos os itens (pesquisa com o campo vazio) o sistema permite incluir apenas um item da listagem como se a configuração do campo permitisse apenas cardinalidade única. Para a reprodução do erro, basta abrir o campo e realizar uma pesquisa sem inserir nenhum termo para a buscar e ao receber a lista de resultados tentar inserir mais de um item.

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
