### ISSUE TITLE
Ferramenta de Reindexacao

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#62]
Ferramenta para reindexar os itens que foram indexados quando inseridos por OAI-PMH, CSV, importacao do pacote tainacan e dspace.

**Comment by juliannyasilva** [comment]
Esta ferramenta foi criada? Se sim, teria como referenciar o commit dela aqui @andre2ar ? Se não retornar ao backlog.

**Comment by juliannyasilva** [comment]
Verificado, implementado.
