### ISSUE TITLE
Desaparecimento - Regra de Negócio - Protótipo IBRAM

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#63]
Ao salvar um registro de desaparecimento o sistema não está alterando o estado dos itens relacionados ao desaparecimento. A funcionalidade deve seguir a seguinte regra:

Regra 114:
(1) Ao solicitar a finalização do registro de Desaparecimento, o sistema deverá
verificar:
(a) Se os campos obrigatórios foram fornecidos
(2) Após as verificações, o sistema deverá:
(a) Criar um registro de Desaparecimento e;
(b) Se no campo “Tipo de ocorrência” for selecionada a opção “Extraviado”, o
sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens
envolvidos” para “Não localizado” e o “Tipo de situação” para “Extraviado”.
Se no campo “Tipo de ocorrência” for selecionada a opção “Furtado”, o sistema
deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos”
para “Não localizado” e o “Tipo de situação” para “Furtado”.
Se no campo “Tipo de ocorrência” for selecionada a opção “Roubado”, o
sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens
envolvidos” para “Não localizado” e o “Tipo de situação” para “Roubado”.

**Comment by juliannyasilva** [comment]
![image](https://user-images.githubusercontent.com/11639242/28795275-a90e147a-760f-11e7-92d7-e1098f81cfd2.png)

## A regra de negocio ainda não esta implementada corretamente.

**Comment by eduardohumberto** [comment]
Boa tarde @juliannyas  testei o desaparecimento do item [ https://medialab.ufg.br/ibram/permanente/mhn-wall ] com o status furtado, na coleção Bem permanente ele alterou a situação,  tem algo a mais?

**Comment by juliannyasilva** [comment]
Não, esta td ok.
