### ISSUE TITLE
[Mobile] Chavear para cards

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#64]
Ao ver uma colecao do tainacan pelo celular, se a listagem estiver sido configurada como modo tabela, alterar automaticamente para o modo cards (pois a tabela não é responsiva). Ou deixar a tabela responsiva.

**Comment by juliannyasilva** [comment]
Verificado, e ainda continua inconsistente. 
![image](https://user-images.githubusercontent.com/11639242/29276718-e1565eb0-80e5-11e7-841f-f0974efd67f0.png)

**Comment by juliannyasilva** [comment]
Foi feito a correção para cards, quando uma coleção esta sendo exibida como tabela.
