### ISSUE TITLE
Ordem da categoria de metadado

### ISSUE THREAD

**Issue by jpmehl** [medialab-ufg/tainacan#7]
Nos metadados de categoria, a ordem de aparição não é a que escolhemos, mas em ordem alfabética. É preciso poder setar o que mais nos interessa. 
Existem alguns casos que isto ficou ruim para nosso projeto: a) Seleção de anos b) seleção de números c) seleçào de esfera governamental

Da pra ver em: http://medialab.ufg.br/democraciadigital/ferramentas/

**Comment by juliannyasilva** [comment]
Verificado, e este site não esta mais disponível, assumindo consequentemente que foi corrigido.
