### ISSUE TITLE
IBRAM] - Metadado relacionamento - Protótipo IBRAM

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#70]
Ao definir em um metadado de relacionamento que não permita a pesquisa de itens já relacionados e o  usuário pesquisa um item já relacionado o sistema não dá nenhum feedback ao usuário. A sugestão seria criar algum mecanismo de feedback ao usuário e manter o campo de pesquisa quando o item já for relacionado.

**Comment by juliannyasilva** [comment]
Verificado, sem inconsistências.
