### ISSUE TITLE
[IBRAM] - Descarte 

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#71]
A funcionalidade de descarte não está alterando o status dos bens relacionados e o registro de descarte está ficando com o campo bens relacionados vazio. A regra ser implementada é a seguinte:

Regra 52:

 

(1)   Ao solicitar a finalização do registro de Descarte, o sistema deverá verificar:

(a)    Se os campos obrigatórios foram fornecidos

 

(2)   Após as verificações, o sistema deverá:

 

(a)    Criar um registro de Descarte e;

 

(b)   Se no campo “Modo” for selecionada a opção “Alienação”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Alienado”.

 

Se no campo “Modo” for selecionada a opção “Cessão”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Cedido”.

 

Se no campo “Modo” for selecionada a opção “Inutilização”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Inutilizado”.

 

Se no campo “Modo” for selecionada a opção “Transferência”, o sistema deverá alterar a “Situação” dos “Bens” informados no campo “Bens envolvidos” para “Registro excluído (Baixa)” e o “Tipo de situação” para “Transferido”.

**Comment by juliannyasilva** [comment]
Verificado e sem inconsistências.
