### ISSUE TITLE
[IBRAM]  - Pesquisa simples e avançada de itens Localização

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#75]
Caso 1: Com uma localização "Bahia" cadastrada no sistema, ao realizar uma busca simples na home da localização com a entrada de busca "Bahia" o sistema informa que não encontrou nenhum item e não trás o item cadastrado.

Caso 2: Nos campos de busca avançada o sistema disponibiliza pro usuário campos que não estão vinculados com os metadados de localização.

Caso 3: Busca avança pelo metadado "tipo de localização" não esta funcionando, não tras items relacionamentos com interna e externa.

Cenario: https://docs.google.com/document/d/1zfV1HbVlnpxLcmqsS-NhzOKUWki3Q_jCRnrgpsgMKAY/edit#

**Comment by juliannyasilva** [comment]
Verificado inconsistências nos buscas simples e avançada. Alguns itens que possuem nome/parte do nome pesquisado não é retornados. Ex: Teste AAA e AAA.

**Comment by eduardohumberto** [comment]
Itens antigos  devem ser atualizados, testar com itens novos a busca

**Comment by juliannyasilva** [comment]
Verificado sem inconsistências.
