### ISSUE TITLE
Imprimir Item - Protótipo IBRAM

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#78]
A impressão do item em formato PDF está com problemas. O formato da data está em formato americano. Os blocos de metadados compostos estão sendo repetidos "Características físicas", "Resumo descritivo", Autores, Outros títulos, Referências bibliográficas estão sendo duplicados no documento PDF. A ordem dos metadados não está de acordo com o formulário de submissão. Os metadados de outras abas como a Administrativo, Requisitos de Conservação  não estão sendo inclusos no arquivo PDF.

**Comment by juliannyas** [comment]
Ainda com as inconsistências apontadas na criação da issue.

**Comment by r-guimaraes** [comment]
Verifique se o servidor está com a versão atualizada

**Comment by juliannyasilva** [comment]
A impressão do item bem permanente (https://ibram.medialab.ufg.br/permanente/perm-completo-0708) que gerou o PDF [perm-completo-01502127832.pdf](https://github.com/medialab-ufg/tainacan/files/1205647/perm-completo-01502127832.pdf), encontrasse com inconsistências em sua impressão.
