### ISSUE TITLE
Moderar registro de novos usuarios

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#82]
Moderar o acesso de novos usuários no sistema, permitindo que o administrador do site decida se o registro de novos usuário ficara ou não disponível a todos.

**Comment by leogermani** [comment]
Na verdade o que temos que fazer é usar todo o esquema de login, registro e esqueci minha senha para o funcionamento padrão do WordPress. Dessa amneira, poderemos usar outros plugins que já fazem esse tipo de coisa
