### ISSUE TITLE
[IBRAM] - Pesquisa Metadado Relacionamento

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#84]
Ao pesquisar um termo 'as' o sistema está retornando resultados como "Aline Lima". em outro caso ao pesquisar 'dad' o sistema retornou "Casa da Moeda do Brasil". Os critérios de busca estão corretos?

**Comment by juliannyasilva** [comment]
Inconsistência: Ao pesquisa por "dad" o sistema retornou itens que não foram parte da sugestão da pesquisa e que não possui em seus dados a nome/parte de nome com o valor "dad".

Cenário: Pesquisando "dad":
![image](https://user-images.githubusercontent.com/11639242/28783870-0e8ed65e-75e8-11e7-80b4-064dffc5ed72.png)

Cenário 2: Clicando na lupa para pesquisar o valor "dad":
![image](https://user-images.githubusercontent.com/11639242/28784013-860bfc48-75e8-11e7-834d-c304438e064f.png)


Possível observação: parece que o sistema esta pegando na busca o nome do metadado e não só o valor, por exemplo, ao retornar o item "tituto vazio" a única referencia ao valor pesquisado e o nome do metadado "Tipo de EntiDADe".

**Comment by eduardohumberto** [comment]
A busca realizada neste local é feita em todos os campos do item, dessa forma ele olha nos valores dos metadados, nome das categorias vinculadas, tags, etc. Pelo que olhei todos os itens (verificar a pagina do item) encontrados tinha essa particula 'dad' .

**Comment by juliannyasilva** [comment]
Verificado sem inconsistências novas encontradas.
