### ISSUE TITLE
[IBRAM] - Restrição de acesso as coleções aos usuários cadastrados como membros e anônimos

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#87]
Mesmo as coleções com configurações de eventos de exclusões bloqueados, usuários sem permissões consegue realizar tais operações diretamente sem passar pela aprovação dos administradores. 

![image](https://user-images.githubusercontent.com/11639242/32729252-41b0d652-c86a-11e7-936f-3ac5d4559174.png)
![image](https://user-images.githubusercontent.com/11639242/32729004-87d2556c-c869-11e7-9d7e-94ae6ab83e86.png)

**Comment by walisonjose** [comment]
É necessário acordar com o IBRAM se tais opções estarão disponíveis e para qual nível de permissão de usuário.
