### ISSUE TITLE
[IBRAM] - Registro de Coleções - Regra 106

### ISSUE THREAD

**Issue by walisonjose** [medialab-ufg/tainacan#90]
O item C) da regra 106 não está implementado:

Não estejam associados à outra coleção cuja “Situação de cadastro” seja
“Ativo” e que não estejam associados a um conjunto cuja situação seja “Ativo” e
que não tenha sido fornecido para o campo “Conjunto de bens”.

**Comment by juliannyas** [comment]
Verificado inconsistências.

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
