### ISSUE TITLE
[IBRAM] - Adição, visualização e alteração de Entidades Coletivas

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#92]
Caso 1: No bloco de dados informações adicionais (Entidade Coletiva):
- Não permite selecionar o país desejado. 
- Os estados são apresentados sem ordem alfabética e com sigla (DF). 
- No campo CNPJ o sistema faz verificação de duplicidade, mais se o usuário não apagar e salvar o item, o sistema não emite nenhuma mensagem de duplicidade para a correção e salva o item zerando o campo CNPJ.

Caso 2: No campo Anexos o botão para inserção de mais anexos esta grudado com o de "Descartar"

Caso 3: No bloco de dados informações organizacionais na busca de entidade mantenedora, o sistema esta trazendo um item "Família Wall&Sons" que é uma família, onde a regra diz para trazer somente as entidades coletivas.

Caso 4: No campo Miniatura o sistema default traz uma imagem quebrada, e se selecionar uma nova, não disponibiliza opção para remoção da imagem(regra não implementada), e ao salvar a entidade o sistema não persiste a imagem definida como miniatura.

Caso 5: Na visualização do item criado o sistema criou o item relacionado com duas "tipo de entidade" sendo esse bloco único, além de quebrar a contração de bloco de dados, não visualização da imagem que foi definida na adição do item e apresentação de um botão em branco sem função implementada (em cima da imagem).

Caso 6: Na home de entidades durante a navegação surge erros de interface no campo "pesquisa" e "download de resultados"

OBS: Testes realizado com usuário nível membro, e não administrador (em admin alguns erros não são repercutidos).

Cenário: https://docs.google.com/document/d/1zfV1HbVlnpxLcmqsS-NhzOKUWki3Q_jCRnrgpsgMKAY/edit#

**Comment by juliannyasilva** [comment]
Inconsistência: Permite adicionar novos campos sem ter preenchido o inicial. Ex: biografias, e referencias bibliográficas.

**Comment by eduardohumberto** [comment]
Funcionará apenas para metadados simples, em referências bibliográficas está como composto, o que dificulta a validação sendo que o composto suporta os mais diferentes tipos, sugiro alterar para simples para validação ou manter este comportamento (o qual não interfere em nenhum momento da execução do adicionar/editar)

**Comment by juliannyasilva** [comment]
**Inconsistência 1**: Permite adicionar uma coletiva com data de criação anterior ao de extinção. Ex. item Testando #92

**Inconsistência 2** : No campo "funções" possui funções extras não pertencentes a entidade coletiva: Editora e Proprietário Anterior.
![image](https://user-images.githubusercontent.com/11639242/28795794-88590c6a-7611-11e7-991f-de7fbe2a196e.png)

**Inconsistência 3**: No campo "informações organizacionais" não esta obedecendo o filtro de buscas de entidades abaixo: 
![image](https://user-images.githubusercontent.com/11639242/28796277-523629cc-7613-11e7-8403-9260e53136e0.png)

**Inconsistência 4**: No campo "Estado/Provincia/Cidade " não esta presente todos os estados do Brasil, faltando os estados (Mato Grosso, Roraima, Sergipe e Tocantins). 
Lista correta segue abaixo:
Acre (AC)
Alagoas (AL)
Amapá (AP)
Amazonas (AM)
Bahia (BA)
Ceará (CE)
Distrito Federal (DF)
Espírito Santo (ES)
Goiás (GO)
Maranhão (MA)
Mato Grosso (MT)
Mato Grosso do Sul (MS)
Minas Gerais (MG)
Pará (PA)
Paraíba (PB)
Paraná (PR)
Pernambuco (PE)
Piauí (PI)
Rio de Janeiro (RJ)
Rio Grande do Norte (RN)
Rio Grande do Sul (RS)
Rondônia (RO)
Roraima (RR)
Santa Catarina (SC)
São Paulo (SP)
Sergipe (SE)
Tocantins (TO)

**Comment by eduardohumberto** [comment]
Inconsistência 2 : Deve se retirar as categorias da categoria Função Entidade Coletiva, tela de administração de categorias

Inconsistência 3:  O metadado faz autocomplete com as entidades, olhando as configurações está selecionado para buscar itens vinculados, com entidade coletiva e família.

Inconsistência 4:  Deve se verificar com o Walison, mas se quiser adicionar manualmente as categorias que faltam, procurar Ibram - cidades e estados na tela de administração de categorias

**Comment by eduardohumberto** [comment]
Inconsistência 1: Os campos do tainacan são gerados dinamicamente,  as datas são criadas    sem saber quais campos foram criados, para fazer essa validação teria que alterado o core do Tainacan, como neste momento estamos com tempo escasso, acredito que pode ser cadastrado uma nova issue como Improvement

**Comment by eduardohumberto** [comment]
vou colocar como validation pois todos são casos são detalhes que podem ser configurados

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
