### ISSUE TITLE
[IBRAM] - Adição, visualização e alteração de Entidade Pessoa

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#93]
Caso 1: No bloco de dados informações adicionais (Entidade Pessoa):
- Os estados são apresentados sem ordem alfabética e com sigla (DF).
- No campo CPF o sistema não faz verificação de duplicidade, o sistema não emite nenhuma mensagem de duplicidade para a correção e salva o item com valor duplicado, sendo que o mesmo era pra ser único.

Caso 2: No campo Anexos o botão para inserção de mais anexos esta grudado com o de "Descartar".

Caso 3: No campo Miniatura o sistema default traz uma imagem quebrada, e se selecionar uma nova, não disponibiliza opção para remoção da imagem(regra não implementada), e ao salvar a entidade o sistema não persiste a imagem definida como miniatura.

Caso 4: não visualização da imagem que foi definida na adição do item e apresentação de um botão em branco sem função implementada (em cima da imagem).

OBS: Testes realizado com usuário nível membro, e não administrador (em admin alguns erros não são repercutidos).

**Comment by juliannyasilva** [comment]
Inconsistência 1: Permite adicionar uma pessoa com data de falecimento anterior ao de nascimento. Ex: Entidade Pessoa 3.

Inconsistência 2: Permite adicionar novos campos sem ter preenchido o inicial. Ex: biografias, e referencias bibliográficas. 

Inconsistência 3 : No campo "funções" não possui a função: Documentador, 

Inconsistência 4: Possui campos extras não pertencentes a entidade pessoa: Personagem de eventos históricos e Proprietário Anterior.

Inconsistência 5: No campo "Estado/Provincia/Cidade " não esta presente todos os estados do Brasil, faltando os estados (Mato Grosso, Roraima, Sergipe e Tocantins). Lista correta segue abaixo: 
Acre (AC)
Alagoas (AL)
Amapá (AP)
Amazonas (AM)
Bahia (BA)
Ceará (CE)
Distrito Federal (DF)
Espírito Santo (ES)
Goiás (GO)
Maranhão (MA)
Mato Grosso (MT)
Mato Grosso do Sul (MS)
Minas Gerais (MG)
Pará (PA)
Paraíba (PB)
Paraná (PR)
Pernambuco (PE)
Piauí (PI)
Rio de Janeiro (RJ)
Rio Grande do Norte (RN)
Rio Grande do Sul (RS)
Rondônia (RO)
Roraima (RR)
Santa Catarina (SC)
São Paulo (SP)
Sergipe (SE)
Tocantins (TO)

**Comment by mbrunodm** [comment]
Inconsistência 1: Mesma situação do caso #92

Inconsistência 2: Esta validação é feita apenas para campos simples, Referências bibliográficas é composto  

Inconsistência 3 e 4 : Retirar categorias  da função Pessoa na tela de administração

Inconsistência 5:  Verificar com o Walison

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
