### ISSUE TITLE
[IBRAM]  - Adição de Desaparecimento

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#95]
Caso 1: De acordo com os requisitos de desenvolvimento não era pra existir o campo "miniatura" na adição de um desaparecimento.

Caso 2: No campo "anexos" exibe uma mensagem que arrastar ou clicar no campo de anexos permite adicionar anexos mas não ocorre o mesmo. E o botão de inserção de anexos não está implementado.

Caso 3: O campo "informações adicionais" não é obrigatório seu preenchimento nos requisitos, mas no sistema esta como obrigatório.

Caso 4: Os filtros de pesquisa no campo "Bens" que é obrigatório, não condiz com os requisitos (tipo e situação), e permite salvar um item com o campo bens obrigatório não preenchido totalmente. 

Caso 5: Não permite a adição e remoção de mais bens, sendo que nos requisitos diz que deveria ter estas opções.

**Comment by juliannyasilva** [comment]
Verificado inconsistências nos casos: 1, 4 e 5.

**Comment by eduardohumberto** [comment]
Caso 1:  Basta entrar em layout, na última aba Estilo da submissão do item e desmarcar 'Habilitar visualização de imagem e anexo'

**Comment by eduardohumberto** [comment]
@juliannyas  O caso 4 é o que está aparecendo itens na situação Excluído? E qual a inconsistência no caso 5?

**Comment by juliannyasilva** [comment]
@eduardohumberto sim, é o caso onde esta aparecendo a situação de excluído, tem que atender a regra 48.
![image](https://user-images.githubusercontent.com/11639242/28734171-02d5f790-73b6-11e7-974a-e7793b268c49.png)

No caso 5 a inconsistência é a fixação dos blocos bens museológicos, bibliográficos e arquivísticos no campo "bens envolvidos". Ou seja, para corrigir é deixar somente um bloco de pesquisa onde possa selecionar vários bens. e caso o usuário queira excluir um bem, é só clicar na lixeira do bem desejado.

**Comment by eduardohumberto** [comment]
O caso 5 é configuração do metadado, porém como foi o @walisonjose  que deixou dessa maneira seria interessante conversar com ele para alterar essa estrutura, acredito que dessa forma atende, porém pois ela se repete em outras coleções.

Alterei o plugin para que ele fizesse essa busca especifica do Ibram, lembre se que nas coleções onde possuir o metadado de relacionamento escolher as categorias  que são usadas no metadado de categoria. Por exemplo o metadado Bens Museologicos deve selecionar a categoria raiz da coleção Bens permanentes ( Já esta selecionado ) e as categorias  '1 - Localizado' e '2 - Não localizado' que estão em baixo da categoria 'Situação - Bens' (Está selecionado outras categorias que não estão vinculados ao metadado de termo)

**Comment by juliannyasilva** [comment]
Caso 4: Ao configurar os metadados do campo "bens envolvidos" para buscar os metadados "situação-bem" do tipo Localizado e Não localizado. O sistema informa que as alterações foram realizadas, mas ele recompõe a configuração, retornado a configuração anterior não considerando a atribuição dos novos metadados de 'situação-bem'.

Caso 5: Verificado e esta correto.

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
