### ISSUE TITLE
[IBRAM]  - Adição de Conjuntos

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#96]
Caso 1: De acordo com os requisitos de desenvolvimento não era pra existir os  campos "miniatura" e "anexos" na adição de um conjunto.

Caso 2: De acordo com os requisitos o campo 'bens' era para disponibilizar opções de adição de novos bens bem como sua remoção, e o sistema não disponibiliza tais opções.

**Comment by juliannyasilva** [comment]
Caso 1: ainda não configurado.

Caso 2: O campo "bens" esta sendo tratado como obrigatório, mas não era pra ser. E não filtra bens de acordo com a regra 100: 
![image](https://user-images.githubusercontent.com/11639242/28730356-3893afa4-73a6-11e7-8e17-0adc401ee3f7.png)

**Comment by mbrunodm** [comment]
Caso 1 - Pode ser corrigido nas configurações.

Caso 2 - Olhar nos comentários do caso #95

**Comment by juliannyasilva** [comment]
Caso 1: foi configurado seu layout, e portando resolvido.

Caso 2: não esta persistindo a configuração dos metadados para categoria "situação-bem".

**Comment by juliannyasilva** [comment]
Os casos semelhantes a este problema foi corrigido, e verifiquei que o caso 2 já se encontra corrigido, poderia encerrar esta issue @mbrunodm ?

**Comment by mbrunodm** [comment]
Corrigido
