### ISSUE TITLE
[IBRAM]  - Visualização de Coleções

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#97]
Caso 1: Lixeira de coleções esta com a paginação dos registros incoerentes, e as colunas em branco sem nomenclatura de identificação.

Caso 2: Colunas da tabela de coleções errada, sem nomenclatura, sendo o espero as seguintes colunas: nome, descrição , situação de cadastro e ações

Caso 3: As buscas em coleções não esta trazendo os resultados corretamente, não trazendo um resultado se informando parte de seu nome.

**Comment by juliannyasilva** [comment]
Inconsistências verificadas nos casos 1, 2 e 3.

**Comment by r-guimaraes** [comment]
Que inconsistências?

**Comment by juliannyasilva** [comment]
Caso 1: colunas sem nomenclatura e fora de ordem na tabela da lixeira.(Nome, descrição, Sit. Cadastro).

Caso 2: colunas sem nomenclatura e fora de ordem na tabela de coleções. (Nome, descrição, Sit. Cadastro).

Caso 3: corrigido.

**Comment by juliannyasilva** [comment]
Verificado, e sem inconsistências.
