### ISSUE TITLE
Os comentarios nao estao sendo computados como contribuicoes no tainacan ontology

### ISSUE THREAD

**Issue by marcelf** [medialab-ufg/tainacan#98]
Nao esta criando eventos para o comentários.

**Comment by juliannyasilva** [comment]
Só esta criando evento para a criação de comentários. Mas como a edição e remoção de comentários na home da coleção esta com erros não foi possível verificar os outros eventos.

**Comment by juliannyas** [comment]
Retorno: De acordo com esta [Gravação](https://drive.google.com/file/d/0B3Y7QqQ4H6oVYTI0R214dEtTOUk/view) podemos visualizar que a busca principal não está trazendo corretamente os dados. Com isto exibir a mensagem de nenhum item encontrado somente quando não houver nenhuma coleção e/ou item que contenha em seu titulo parte do valor procurado.

**Comment by juliannyasilva** [comment]
Corrigido.
