### ISSUE TITLE
[IBRAM]  - Adição de Descarte(Baixa)

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#99]
Caso 1: De acordo com os requisitos de desenvolvimento não era pra existir o campo "miniatura" na adição de um descarte.

Caso 2: No campo "anexos" exibe uma mensagem que arrastar ou clicar no campo de anexos permite adicionar anexos mas não ocorre o mesmo. E o botão de inserção de anexos não está implementado.

Caso 3: No campo "responsável" permite selecionar varias entidades e adiciona-las, mas no campo "destinatário" não permite adicionar varias entidades, porque? Sendo que nos requisitos não especifica isso...

Caso 4: O campo "informações adicionais" não é obrigatório seu preenchimento nos requisitos, mas no sistema esta como obrigatório. 

Caso 5: Os filtros de pesquisa no campo "Bens" que é obrigatório, não condiz com os requisitos (tipo e situação).

Caso 6: Sistema permite salvar um item com o campo bens obrigatório não preenchido totalmente.

**Comment by juliannyasilva** [comment]
Caso 1: não configurado.

Caso 4: não resolvido.

Caso 5: não implementa a regra 48. (esta trazendo coleções do tipo temporário).
![image](https://user-images.githubusercontent.com/11639242/28731880-12bc6fa4-73ac-11e7-81cf-3fb886004ce6.png)

Caso 6: não corrigido.

**Comment by eduardohumberto** [comment]
Caso 1: Basta entrar em layout, na última aba Estilo da submissão do item e desmarcar 'Habilitar visualização de imagem e anexo'

**Comment by juliannyasilva** [comment]
Caso 1: configurado.

**Comment by eduardohumberto** [comment]
Caso 4: configurar metadado para não ser obrigatório

Caso 6:  Este campo permite apenas que um dos campo seja preenchido, não sendo necessário todos os campos

**Comment by eduardohumberto** [comment]
Caso 5 verificar o exemplo do caso #95

**Comment by juliannyasilva** [comment]
caso 5: verificado e esta realizando o filtro corretamente.

**Comment by juliannyas** [comment]
![image](https://user-images.githubusercontent.com/11639242/29793292-b6a4e558-8c19-11e7-939f-6ca567201ca3.png)

- [ ] A regra não esta implementada corretamente, pois no auto complete esta trazendo bens temporários, alem de bens que não estão disponíveis para relacionamento.

![image](https://user-images.githubusercontent.com/11639242/29793418-14bd8708-8c1a-11e7-9d68-49fed33f867a.png)

**Comment by juliannyasilva** [comment]
Retorno: Ao tentar criar um descarte, ocorreu ao salvar um travamento como pode ser visto no video : https://drive.google.com/file/d/0B3Y7QqQ4H6oVS3ZpMGdMMlIyOGM/view

E ao atualizar a pagina, gerou os seguintes erros: https://drive.google.com/file/d/0B3Y7QqQ4H6oVa1NJUWtzTTlfU0U/view
![image](https://user-images.githubusercontent.com/11639242/30126362-1f730192-9312-11e7-9c69-749541d7d859.png)

**Comment by eduardohumberto** [comment]
Testar novamente
